-- RBAC Admin Portal schema for Oracle Database
-- Based on screens in rbac-admin-portal.html:
-- Modules, Pages, Actions, Roles, Geo Scope, User Groups, Users

-- ============================================================
-- 1) MASTER TABLES
-- ============================================================

CREATE TABLE rbac_company (
    company_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code        VARCHAR2(30) NOT NULL,
    company_name        VARCHAR2(120) NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT uq_rbac_company_code UNIQUE (company_code),
    CONSTRAINT ck_rbac_company_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE', 'DRAFT'))
);

CREATE TABLE rbac_department (
    department_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          NUMBER NOT NULL,
    department_code     VARCHAR2(30) NOT NULL,
    department_name     VARCHAR2(120) NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT fk_rbac_dept_company
        FOREIGN KEY (company_id) REFERENCES rbac_company(company_id),
    CONSTRAINT uq_rbac_dept_comp_code UNIQUE (company_id, department_code),
    CONSTRAINT ck_rbac_dept_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_rbac_dept_company ON rbac_department(company_id);

CREATE TABLE rbac_country (
    country_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso2_code           CHAR(2) NOT NULL,
    country_name        VARCHAR2(120) NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT uq_rbac_country_iso2 UNIQUE (iso2_code),
    CONSTRAINT uq_rbac_country_name UNIQUE (country_name),
    CONSTRAINT ck_rbac_country_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE rbac_embassy (
    embassy_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id          NUMBER NOT NULL,
    embassy_code        VARCHAR2(40) NOT NULL,
    embassy_name        VARCHAR2(200) NOT NULL,
    embassy_type_cd     VARCHAR2(30) DEFAULT 'EMBASSY' NOT NULL,
    city_name           VARCHAR2(120),
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_rbac_emb_country
        FOREIGN KEY (country_id) REFERENCES rbac_country(country_id),
    CONSTRAINT uq_rbac_emb_code UNIQUE (embassy_code),
    CONSTRAINT uq_rbac_emb_country_name UNIQUE (country_id, embassy_name),
    CONSTRAINT ck_rbac_emb_type
        CHECK (embassy_type_cd IN ('EMBASSY', 'CONSULATE', 'HIGH_COMMISSION', 'OTHER')),
    CONSTRAINT ck_rbac_emb_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_rbac_emb_country ON rbac_embassy(country_id);

-- ============================================================
-- 2) MODULE / PAGE / ACTION (PERMISSION CATALOG)
-- ============================================================

CREATE TABLE rbac_module (
    module_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code         VARCHAR2(30) NOT NULL,
    module_name         VARCHAR2(120) NOT NULL,
    icon_name           VARCHAR2(20),
    description_txt     VARCHAR2(1000),
    sort_order          NUMBER(6) DEFAULT 0 NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT uq_rbac_module_code UNIQUE (module_code),
    CONSTRAINT uq_rbac_module_name UNIQUE (module_name),
    CONSTRAINT ck_rbac_module_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE rbac_page (
    page_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id           NUMBER NOT NULL,
    page_code           VARCHAR2(40) NOT NULL,
    page_name           VARCHAR2(150) NOT NULL,
    route_path          VARCHAR2(300),
    description_txt     VARCHAR2(1000),
    sort_order          NUMBER(6) DEFAULT 0 NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT fk_rbac_page_module
        FOREIGN KEY (module_id) REFERENCES rbac_module(module_id),
    CONSTRAINT uq_rbac_page_code UNIQUE (page_code),
    CONSTRAINT uq_rbac_page_mod_name UNIQUE (module_id, page_name),
    CONSTRAINT ck_rbac_page_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_rbac_page_module ON rbac_page(module_id);

CREATE TABLE rbac_action (
    action_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id             NUMBER NOT NULL,
    action_code         VARCHAR2(60) NOT NULL,
    action_name         VARCHAR2(150) NOT NULL,
    action_type_cd      VARCHAR2(20) NOT NULL,
    description_txt     VARCHAR2(1000),
    sort_order          NUMBER(6) DEFAULT 0 NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT fk_rbac_action_page
        FOREIGN KEY (page_id) REFERENCES rbac_page(page_id),
    CONSTRAINT uq_rbac_action_code UNIQUE (action_code),
    CONSTRAINT uq_rbac_action_page_type UNIQUE (page_id, action_type_cd),
    CONSTRAINT ck_rbac_action_type
        CHECK (action_type_cd IN ('VIEW', 'ADD', 'EDIT', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'CUSTOM')),
    CONSTRAINT ck_rbac_action_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_rbac_action_page ON rbac_action(page_id);

-- ============================================================
-- 3) ROLES AND ROLE-PERMISSIONS
-- ============================================================

CREATE TABLE rbac_role (
    role_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code           VARCHAR2(40) NOT NULL,
    role_name           VARCHAR2(150) NOT NULL,
    description_txt     VARCHAR2(1000),
    access_model_cd     VARCHAR2(20) DEFAULT 'USER_LINKED' NOT NULL,
    scope_level_cd      VARCHAR2(20) DEFAULT 'GLOBAL' NOT NULL,
    is_system_role      CHAR(1) DEFAULT 'N' NOT NULL,
    is_super_admin_role CHAR(1) DEFAULT 'N' NOT NULL,
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT uq_rbac_role_code UNIQUE (role_code),
    CONSTRAINT uq_rbac_role_name UNIQUE (role_name),
    CONSTRAINT ck_rbac_role_access_model
        CHECK (access_model_cd IN ('USER_LINKED', 'GEO_SCOPED', 'GROUP_LINKED')),
    CONSTRAINT ck_rbac_role_scope_level
        CHECK (scope_level_cd IN ('GLOBAL', 'COUNTRY', 'EMBASSY')),
    CONSTRAINT ck_rbac_role_sys
        CHECK (is_system_role IN ('Y', 'N')),
    CONSTRAINT ck_rbac_role_super
        CHECK (is_super_admin_role IN ('Y', 'N')),
    CONSTRAINT ck_rbac_role_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE', 'DRAFT'))
);

CREATE INDEX ix_rbac_role_access_model ON rbac_role(access_model_cd);

CREATE TABLE rbac_role_permission (
    role_id             NUMBER NOT NULL,
    action_id           NUMBER NOT NULL,
    grant_flag          CHAR(1) DEFAULT 'Y' NOT NULL,
    granted_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    granted_by          VARCHAR2(128),
    CONSTRAINT pk_rbac_role_perm PRIMARY KEY (role_id, action_id),
    CONSTRAINT fk_rbac_role_perm_role
        FOREIGN KEY (role_id) REFERENCES rbac_role(role_id),
    CONSTRAINT fk_rbac_role_perm_action
        FOREIGN KEY (action_id) REFERENCES rbac_action(action_id),
    CONSTRAINT ck_rbac_role_perm_grant
        CHECK (grant_flag IN ('Y', 'N'))
);

CREATE INDEX ix_rbac_role_perm_action ON rbac_role_permission(action_id);

-- Geo-scoped restrictions for GEO_SCOPED roles
CREATE TABLE rbac_role_country_scope (
    role_id             NUMBER NOT NULL,
    country_id          NUMBER NOT NULL,
    CONSTRAINT pk_rbac_role_country_scope PRIMARY KEY (role_id, country_id),
    CONSTRAINT fk_rbac_role_country_scope_role
        FOREIGN KEY (role_id) REFERENCES rbac_role(role_id),
    CONSTRAINT fk_rbac_role_country_scope_country
        FOREIGN KEY (country_id) REFERENCES rbac_country(country_id)
);

CREATE INDEX ix_rbac_role_country_scope_country ON rbac_role_country_scope(country_id);

CREATE TABLE rbac_role_embassy_scope (
    role_id             NUMBER NOT NULL,
    embassy_id          NUMBER NOT NULL,
    CONSTRAINT pk_rbac_role_emb_scope PRIMARY KEY (role_id, embassy_id),
    CONSTRAINT fk_rbac_role_emb_scope_role
        FOREIGN KEY (role_id) REFERENCES rbac_role(role_id),
    CONSTRAINT fk_rbac_role_emb_scope_emb
        FOREIGN KEY (embassy_id) REFERENCES rbac_embassy(embassy_id)
);

CREATE INDEX ix_rbac_role_emb_scope_emb ON rbac_role_embassy_scope(embassy_id);

-- ============================================================
-- 4) USER MASTER + ROLE MAPPING
-- ============================================================

CREATE TABLE rbac_user_account (
    user_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         VARCHAR2(40) NOT NULL,
    first_name          VARCHAR2(80) NOT NULL,
    last_name           VARCHAR2(80) NOT NULL,
    email_addr          VARCHAR2(255) NOT NULL,
    designation         VARCHAR2(120),
    company_id          NUMBER,
    department_id       NUMBER,
    external_subject_id VARCHAR2(200),
    status_cd           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(128),
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(128),
    CONSTRAINT uq_rbac_user_employee UNIQUE (employee_id),
    CONSTRAINT uq_rbac_user_email UNIQUE (email_addr),
    CONSTRAINT fk_rbac_user_company
        FOREIGN KEY (company_id) REFERENCES rbac_company(company_id),
    CONSTRAINT fk_rbac_user_dept
        FOREIGN KEY (department_id) REFERENCES rbac_department(department_id),
    CONSTRAINT ck_rbac_user_status
        CHECK (status_cd IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE INDEX ix_rbac_user_company ON rbac_user_account(company_id);
CREATE INDEX ix_rbac_user_dept ON rbac_user_account(department_id);

CREATE TABLE rbac_user_role (
    user_id             NUMBER NOT NULL,
    role_id             NUMBER NOT NULL,
    valid_from          DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    valid_to            DATE,
    assigned_reason     VARCHAR2(500),
    assigned_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    assigned_by         VARCHAR2(128),
    CONSTRAINT pk_rbac_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_rbac_user_role_user
        FOREIGN KEY (user_id) REFERENCES rbac_user_account(user_id),
    CONSTRAINT fk_rbac_user_role_role
        FOREIGN KEY (role_id) REFERENCES rbac_role(role_id),
    CONSTRAINT ck_rbac_user_role_dates
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_rbac_user_role_role ON rbac_user_role(role_id);

-- ============================================================
-- 5) GROUP-BASED ACCESS (COMPANY / TEAM MODEL)
-- ============================================================

CREATE TABLE rbac_user_group (
    group_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           NUMBER NOT NULL,
    group_code           VARCHAR2(50),
    group_name           VARCHAR2(150) NOT NULL,
    group_type_cd        VARCHAR2(30) NOT NULL,
    description_txt      VARCHAR2(1000),
    role_template_role_id NUMBER,
    estimated_members    NUMBER(8),
    membership_source_cd VARCHAR2(30) DEFAULT 'ORG_CHART' NOT NULL,
    status_cd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by           VARCHAR2(128),
    updated_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by           VARCHAR2(128),
    CONSTRAINT fk_rbac_group_company
        FOREIGN KEY (company_id) REFERENCES rbac_company(company_id),
    CONSTRAINT fk_rbac_group_role_tmpl
        FOREIGN KEY (role_template_role_id) REFERENCES rbac_role(role_id),
    CONSTRAINT uq_rbac_group_comp_name UNIQUE (company_id, group_name),
    CONSTRAINT uq_rbac_group_code UNIQUE (group_code),
    CONSTRAINT ck_rbac_group_type
        CHECK (group_type_cd IN ('DEPARTMENT_TEAM', 'PUBLIC_GROUP', 'EXTERNAL_PARTNER')),
    CONSTRAINT ck_rbac_group_member_src
        CHECK (membership_source_cd IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL', 'PUBLIC')),
    CONSTRAINT ck_rbac_group_status
        CHECK (status_cd IN ('ACTIVE', 'DRAFT', 'INACTIVE'))
);

CREATE INDEX ix_rbac_group_company ON rbac_user_group(company_id);

-- Optional direct user membership for systems that persist org-chart groups
CREATE TABLE rbac_group_membership (
    group_id             NUMBER NOT NULL,
    user_id              NUMBER NOT NULL,
    membership_source_cd VARCHAR2(30) DEFAULT 'ORG_CHART' NOT NULL,
    valid_from           DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    valid_to             DATE,
    CONSTRAINT pk_rbac_group_membership PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_rbac_group_mem_group
        FOREIGN KEY (group_id) REFERENCES rbac_user_group(group_id),
    CONSTRAINT fk_rbac_group_mem_user
        FOREIGN KEY (user_id) REFERENCES rbac_user_account(user_id),
    CONSTRAINT ck_rbac_group_mem_source
        CHECK (membership_source_cd IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL')),
    CONSTRAINT ck_rbac_group_mem_dates
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_rbac_group_mem_user ON rbac_group_membership(user_id);

-- Group-to-role linkage (Group-Linked access model)
CREATE TABLE rbac_group_role (
    group_id             NUMBER NOT NULL,
    role_id              NUMBER NOT NULL,
    assigned_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    assigned_by          VARCHAR2(128),
    CONSTRAINT pk_rbac_group_role PRIMARY KEY (group_id, role_id),
    CONSTRAINT fk_rbac_group_role_group
        FOREIGN KEY (group_id) REFERENCES rbac_user_group(group_id),
    CONSTRAINT fk_rbac_group_role_role
        FOREIGN KEY (role_id) REFERENCES rbac_role(role_id)
);

CREATE INDEX ix_rbac_group_role_role ON rbac_group_role(role_id);

-- Optional group-specific permission overrides (for Group Module Access screen)
CREATE TABLE rbac_group_permission (
    group_id             NUMBER NOT NULL,
    action_id            NUMBER NOT NULL,
    grant_flag           CHAR(1) DEFAULT 'Y' NOT NULL,
    granted_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    granted_by           VARCHAR2(128),
    CONSTRAINT pk_rbac_group_perm PRIMARY KEY (group_id, action_id),
    CONSTRAINT fk_rbac_group_perm_group
        FOREIGN KEY (group_id) REFERENCES rbac_user_group(group_id),
    CONSTRAINT fk_rbac_group_perm_action
        FOREIGN KEY (action_id) REFERENCES rbac_action(action_id),
    CONSTRAINT ck_rbac_group_perm_grant
        CHECK (grant_flag IN ('Y', 'N'))
);

CREATE INDEX ix_rbac_group_perm_action ON rbac_group_permission(action_id);

-- ============================================================
-- 6) AUDIT LOG
-- ============================================================

CREATE TABLE rbac_audit_log (
    audit_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_ts             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    actor_user_id        NUMBER,
    event_type_cd        VARCHAR2(60) NOT NULL,
    entity_type_cd       VARCHAR2(60) NOT NULL,
    entity_pk            VARCHAR2(120),
    detail_json          CLOB,
    ip_address           VARCHAR2(64),
    user_agent           VARCHAR2(1000),
    CONSTRAINT fk_rbac_audit_actor
        FOREIGN KEY (actor_user_id) REFERENCES rbac_user_account(user_id),
    CONSTRAINT ck_rbac_audit_json
        CHECK (detail_json IS JSON)
);

CREATE INDEX ix_rbac_audit_event_ts ON rbac_audit_log(event_ts);
CREATE INDEX ix_rbac_audit_actor ON rbac_audit_log(actor_user_id);
CREATE INDEX ix_rbac_audit_entity ON rbac_audit_log(entity_type_cd, entity_pk);

-- ============================================================
-- 7) HELPER VIEW: EFFECTIVE USER ACTIONS
-- ============================================================
-- Combines:
--   a) direct user-role permissions
--   b) group-role permissions
--   c) direct group permissions
CREATE OR REPLACE VIEW v_rbac_effective_user_action AS
SELECT DISTINCT
    u.user_id,
    rp.action_id,
    'USER_ROLE' AS source_type
FROM rbac_user_account u
JOIN rbac_user_role ur
  ON ur.user_id = u.user_id
JOIN rbac_role_permission rp
  ON rp.role_id = ur.role_id
WHERE rp.grant_flag = 'Y'
  AND (ur.valid_to IS NULL OR ur.valid_to >= TRUNC(SYSDATE))

UNION ALL

SELECT DISTINCT
    gm.user_id,
    rp.action_id,
    'GROUP_ROLE' AS source_type
FROM rbac_group_membership gm
JOIN rbac_group_role gr
  ON gr.group_id = gm.group_id
JOIN rbac_role_permission rp
  ON rp.role_id = gr.role_id
WHERE rp.grant_flag = 'Y'
  AND (gm.valid_to IS NULL OR gm.valid_to >= TRUNC(SYSDATE))

UNION ALL

SELECT DISTINCT
    gm.user_id,
    gp.action_id,
    'GROUP_PERMISSION' AS source_type
FROM rbac_group_membership gm
JOIN rbac_group_permission gp
  ON gp.group_id = gm.group_id
WHERE gp.grant_flag = 'Y'
  AND (gm.valid_to IS NULL OR gm.valid_to >= TRUNC(SYSDATE));

-- End of schema
