-- RBAC Admin Portal schema for Oracle Database
-- Naming convention requested:
--   * Master tables      : TblMstRBAC...
--   * Transaction tables : TblTrnRBAC...
--   * Primary key names  : ...Uno
--   * All primary keys are identity columns.
-- Bilingual support:
--   * English columns use suffix En (VARCHAR2)
--   * Arabic columns use suffix Ar (NVARCHAR2)
-- Audit fields:
--   * EnteredOn, EnteredBy, ModifiedOn, ModifiedBy, DeletedOn, DeletedBy
-- Active flag:
--   * IsActive NUMBER(1) in all tables (1=active, 0=inactive)

-- ============================================================
-- 1) MASTER TABLES (TblMstRBAC*)
-- ============================================================

CREATE TABLE TblMstRBACCompany (
    CompanyUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyCode         VARCHAR2(30) NOT NULL,
    CompanyNameEn       VARCHAR2(120) NOT NULL,
    CompanyNameAr       NVARCHAR2(120),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstCompany_Code UNIQUE (CompanyCode),
    CONSTRAINT CK_MstCompany_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblMstRBACDepartment (
    DepartmentUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyUno          NUMBER NOT NULL,
    DepartmentCode      VARCHAR2(30) NOT NULL,
    DepartmentNameEn    VARCHAR2(120) NOT NULL,
    DepartmentNameAr    NVARCHAR2(120),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_MstDept_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT UQ_MstDept_CompCode UNIQUE (CompanyUno, DepartmentCode),
    CONSTRAINT CK_MstDept_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstDept_Company ON TblMstRBACDepartment(CompanyUno);

CREATE TABLE TblMstRBACCountry (
    CountryUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Iso2Code            CHAR(2) NOT NULL,
    CountryNameEn       VARCHAR2(120) NOT NULL,
    CountryNameAr       NVARCHAR2(120),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstCountry_Iso2 UNIQUE (Iso2Code),
    CONSTRAINT UQ_MstCountry_NameEn UNIQUE (CountryNameEn),
    CONSTRAINT CK_MstCountry_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblMstRBACEmbassy (
    EmbassyUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CountryUno          NUMBER NOT NULL,
    EmbassyCode         VARCHAR2(40) NOT NULL,
    EmbassyNameEn       VARCHAR2(200) NOT NULL,
    EmbassyNameAr       NVARCHAR2(200),
    EmbassyTypeCd       VARCHAR2(30) DEFAULT 'EMBASSY' NOT NULL,
    CityNameEn          VARCHAR2(120),
    CityNameAr          NVARCHAR2(120),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_MstEmb_Country FOREIGN KEY (CountryUno) REFERENCES TblMstRBACCountry(CountryUno),
    CONSTRAINT UQ_MstEmb_Code UNIQUE (EmbassyCode),
    CONSTRAINT UQ_MstEmb_CountryEn UNIQUE (CountryUno, EmbassyNameEn),
    CONSTRAINT CK_MstEmb_Type CHECK (EmbassyTypeCd IN ('EMBASSY', 'CONSULATE', 'HIGH_COMMISSION', 'OTHER')),
    CONSTRAINT CK_MstEmb_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstEmb_Country ON TblMstRBACEmbassy(CountryUno);

CREATE TABLE TblMstRBACModule (
    ModuleUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleCode          VARCHAR2(30) NOT NULL,
    ModuleNameEn        VARCHAR2(120) NOT NULL,
    ModuleNameAr        NVARCHAR2(120),
    IconName            VARCHAR2(20),
    DescriptionEn       VARCHAR2(1000),
    DescriptionAr       NVARCHAR2(1000),
    SortOrder           NUMBER(6) DEFAULT 0 NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstModule_Code UNIQUE (ModuleCode),
    CONSTRAINT UQ_MstModule_NameEn UNIQUE (ModuleNameEn),
    CONSTRAINT CK_MstModule_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblMstRBACPage (
    PageUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleUno           NUMBER NOT NULL,
    PageCode            VARCHAR2(40) NOT NULL,
    PageNameEn          VARCHAR2(150) NOT NULL,
    PageNameAr          NVARCHAR2(150),
    RoutePath           VARCHAR2(300),
    DescriptionEn       VARCHAR2(1000),
    DescriptionAr       NVARCHAR2(1000),
    SortOrder           NUMBER(6) DEFAULT 0 NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_MstPage_Module FOREIGN KEY (ModuleUno) REFERENCES TblMstRBACModule(ModuleUno),
    CONSTRAINT UQ_MstPage_Code UNIQUE (PageCode),
    CONSTRAINT UQ_MstPage_ModNameEn UNIQUE (ModuleUno, PageNameEn),
    CONSTRAINT CK_MstPage_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstPage_Module ON TblMstRBACPage(ModuleUno);

CREATE TABLE TblMstRBACAction (
    ActionUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PageUno             NUMBER NOT NULL,
    ActionCode          VARCHAR2(60) NOT NULL,
    ActionNameEn        VARCHAR2(150) NOT NULL,
    ActionNameAr        NVARCHAR2(150),
    ActionTypeCd        VARCHAR2(20) NOT NULL,
    DescriptionEn       VARCHAR2(1000),
    DescriptionAr       NVARCHAR2(1000),
    SortOrder           NUMBER(6) DEFAULT 0 NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_MstAction_Page FOREIGN KEY (PageUno) REFERENCES TblMstRBACPage(PageUno),
    CONSTRAINT UQ_MstAction_Code UNIQUE (ActionCode),
    CONSTRAINT UQ_MstAction_PageType UNIQUE (PageUno, ActionTypeCd),
    CONSTRAINT CK_MstAction_Type CHECK (ActionTypeCd IN ('VIEW', 'ADD', 'EDIT', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'CUSTOM')),
    CONSTRAINT CK_MstAction_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstAction_Page ON TblMstRBACAction(PageUno);

CREATE TABLE TblMstRBACRole (
    RoleUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleCode            VARCHAR2(40) NOT NULL,
    RoleNameEn          VARCHAR2(150) NOT NULL,
    RoleNameAr          NVARCHAR2(150),
    DescriptionEn       VARCHAR2(1000),
    DescriptionAr       NVARCHAR2(1000),
    AccessModelCd       VARCHAR2(20) DEFAULT 'USER_LINKED' NOT NULL,
    ScopeLevelCd        VARCHAR2(20) DEFAULT 'GLOBAL' NOT NULL,
    IsSystemRole        CHAR(1) DEFAULT 'N' NOT NULL,
    IsSuperAdminRole    CHAR(1) DEFAULT 'N' NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT CK_MstRole_AccessModel CHECK (AccessModelCd IN ('USER_LINKED', 'GEO_SCOPED', 'GROUP_LINKED')),
    CONSTRAINT CK_MstRole_ScopeLevel CHECK (ScopeLevelCd IN ('GLOBAL', 'COUNTRY', 'EMBASSY')),
    CONSTRAINT CK_MstRole_IsSystem CHECK (IsSystemRole IN ('Y', 'N')),
    CONSTRAINT CK_MstRole_IsSuper CHECK (IsSuperAdminRole IN ('Y', 'N')),
    CONSTRAINT CK_MstRole_IsActive CHECK (IsActive IN (0, 1)),
    CONSTRAINT CK_MstRole_DelActive CHECK (DeletedOn IS NULL OR IsActive = 0)
);

-- Allow reuse of code/name after soft-delete (DeletedOn is not null)
CREATE UNIQUE INDEX UX_MstRole_Code_Act
    ON TblMstRBACRole (CASE WHEN DeletedOn IS NULL THEN RoleCode END);

CREATE UNIQUE INDEX UX_MstRole_NameEn_Act
    ON TblMstRBACRole (CASE WHEN DeletedOn IS NULL THEN RoleNameEn END);

CREATE INDEX IX_MstRole_AccessModel ON TblMstRBACRole(AccessModelCd);

CREATE TABLE TblMstRBACUser (
    UserUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeId          VARCHAR2(40) NOT NULL,
    FirstNameEn         VARCHAR2(80) NOT NULL,
    FirstNameAr         NVARCHAR2(80),
    LastNameEn          VARCHAR2(80) NOT NULL,
    LastNameAr          NVARCHAR2(80),
    EmailAddr           VARCHAR2(255) NOT NULL,
    DesignationEn       VARCHAR2(120),
    DesignationAr       NVARCHAR2(120),
    CompanyUno          NUMBER,
    DepartmentUno       NUMBER,
    ExternalSubjectId   VARCHAR2(200),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstUser_Emp UNIQUE (EmployeeId),
    CONSTRAINT UQ_MstUser_Email UNIQUE (EmailAddr),
    CONSTRAINT FK_MstUser_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT FK_MstUser_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstRBACDepartment(DepartmentUno),
    CONSTRAINT CK_MstUser_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstUser_Company ON TblMstRBACUser(CompanyUno);
CREATE INDEX IX_MstUser_Department ON TblMstRBACUser(DepartmentUno);

CREATE TABLE TblMstRBACUserGroup (
    UserGroupUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyUno          NUMBER NOT NULL,
    GroupCode           VARCHAR2(50),
    GroupNameEn         VARCHAR2(150) NOT NULL,
    GroupNameAr         NVARCHAR2(150),
    GroupTypeCd         VARCHAR2(30) NOT NULL,
    DescriptionEn       VARCHAR2(1000),
    DescriptionAr       NVARCHAR2(1000),
    RoleTemplateUno     NUMBER,
    EstimatedMembers    NUMBER(8),
    MembershipSourceCd  VARCHAR2(30) DEFAULT 'ORG_CHART' NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_MstUserGroup_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT FK_MstUserGroup_RoleTpl FOREIGN KEY (RoleTemplateUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_MstUserGroup_CompEn UNIQUE (CompanyUno, GroupNameEn),
    CONSTRAINT UQ_MstUserGroup_Code UNIQUE (GroupCode),
    CONSTRAINT CK_MstUserGroup_Type CHECK (GroupTypeCd IN ('DEPARTMENT_TEAM', 'PUBLIC_GROUP', 'EXTERNAL_PARTNER')),
    CONSTRAINT CK_MstUserGroup_Source CHECK (MembershipSourceCd IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL', 'PUBLIC')),
    CONSTRAINT CK_MstUserGroup_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstUserGroup_Company ON TblMstRBACUserGroup(CompanyUno);

-- ============================================================
-- 2) TRANSACTION TABLES (TblTrnRBAC*)
-- ============================================================

CREATE TABLE TblTrnRBACRoleCountryScope (
    RoleCountryScopeUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleUno             NUMBER NOT NULL,
    CountryUno          NUMBER NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnRoleCtry_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRoleCtry_Country FOREIGN KEY (CountryUno) REFERENCES TblMstRBACCountry(CountryUno),
    CONSTRAINT UQ_TrnRoleCtry UNIQUE (RoleUno, CountryUno),
    CONSTRAINT CK_TrnRoleCtry_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnRoleCtry_Country ON TblTrnRBACRoleCountryScope(CountryUno);

CREATE TABLE TblTrnRBACRoleEmbassyScope (
    RoleEmbassyScopeUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleUno             NUMBER NOT NULL,
    EmbassyUno          NUMBER NOT NULL,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnRoleEmb_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRoleEmb_Embassy FOREIGN KEY (EmbassyUno) REFERENCES TblMstRBACEmbassy(EmbassyUno),
    CONSTRAINT UQ_TrnRoleEmb UNIQUE (RoleUno, EmbassyUno),
    CONSTRAINT CK_TrnRoleEmb_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnRoleEmb_Embassy ON TblTrnRBACRoleEmbassyScope(EmbassyUno);

CREATE TABLE TblTrnRBACUserRole (
    UserRoleUno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno             NUMBER NOT NULL,
    RoleUno             NUMBER NOT NULL,
    ValidFrom           DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    ValidTo             DATE,
    AssignedReason      VARCHAR2(500),
    AssignedAt          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    AssignedBy          VARCHAR2(128),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnUserRole_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserRole_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_TrnUserRole UNIQUE (UserUno, RoleUno),
    CONSTRAINT CK_TrnUserRole_Dates CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom),
    CONSTRAINT CK_TrnUserRole_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserRole_Role ON TblTrnRBACUserRole(RoleUno);

CREATE TABLE TblTrnRBACGroupMembership (
    GroupMembershipUno  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserGroupUno        NUMBER NOT NULL,
    UserUno             NUMBER NOT NULL,
    MembershipSourceCd  VARCHAR2(30) DEFAULT 'ORG_CHART' NOT NULL,
    ValidFrom           DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    ValidTo             DATE,
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnGroupMem_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnGroupMem_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT UQ_TrnGroupMembership UNIQUE (UserGroupUno, UserUno),
    CONSTRAINT CK_TrnGroupMem_Source CHECK (MembershipSourceCd IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL')),
    CONSTRAINT CK_TrnGroupMem_Dates CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom),
    CONSTRAINT CK_TrnGroupMem_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnGroupMem_User ON TblTrnRBACGroupMembership(UserUno);

CREATE TABLE TblTrnRBACGroupRole (
    GroupRoleUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserGroupUno        NUMBER NOT NULL,
    RoleUno             NUMBER NOT NULL,
    AssignedAt          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    AssignedBy          VARCHAR2(128),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnGroupRole_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnGroupRole_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_TrnGroupRole UNIQUE (UserGroupUno, RoleUno),
    CONSTRAINT CK_TrnGroupRole_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnGroupRole_Role ON TblTrnRBACGroupRole(RoleUno);

-- GranteeTypeCd='ROLE'  => RoleUno is used
-- GranteeTypeCd='GROUP' => UserGroupUno is used
CREATE TABLE TblTrnRBACPermission (
    PermissionUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GranteeTypeCd       VARCHAR2(20) NOT NULL,
    RoleUno             NUMBER,
    UserGroupUno        NUMBER,
    ActionUno           NUMBER NOT NULL,
    GrantFlag           CHAR(1) DEFAULT 'Y' NOT NULL,
    GrantedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    GrantedBy           VARCHAR2(128),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnPerm_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnPerm_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnPerm_Action FOREIGN KEY (ActionUno) REFERENCES TblMstRBACAction(ActionUno),
    CONSTRAINT CK_TrnPerm_Grantee CHECK (GranteeTypeCd IN ('ROLE', 'GROUP')),
    CONSTRAINT CK_TrnPerm_GrantFlag CHECK (GrantFlag IN ('Y', 'N')),
    CONSTRAINT CK_TrnPerm_GranteeRef CHECK (
        (GranteeTypeCd = 'ROLE' AND RoleUno IS NOT NULL AND UserGroupUno IS NULL) OR
        (GranteeTypeCd = 'GROUP' AND UserGroupUno IS NOT NULL AND RoleUno IS NULL)
    ),
    CONSTRAINT UQ_TrnPermission UNIQUE (GranteeTypeCd, RoleUno, UserGroupUno, ActionUno),
    CONSTRAINT CK_TrnPerm_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnPerm_Action ON TblTrnRBACPermission(ActionUno);
CREATE INDEX IX_TrnPerm_Role ON TblTrnRBACPermission(RoleUno);
CREATE INDEX IX_TrnPerm_Group ON TblTrnRBACPermission(UserGroupUno);

CREATE TABLE TblTrnRBACAuditLog (
    AuditUno            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EventTs             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ActorUserUno        NUMBER,
    EventTypeCd         VARCHAR2(60) NOT NULL,
    EntityTypeCd        VARCHAR2(60) NOT NULL,
    EntityPk            VARCHAR2(120),
    DetailJson          CLOB,
    IpAddress           VARCHAR2(64),
    UserAgent           VARCHAR2(1000),
    IsActive            NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy           VARCHAR2(128),
    ModifiedOn          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR2(128),
    DeletedOn           TIMESTAMP(6),
    DeletedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnAudit_Actor FOREIGN KEY (ActorUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnAudit_Json CHECK (DetailJson IS JSON),
    CONSTRAINT CK_TrnAudit_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnAudit_EventTs ON TblTrnRBACAuditLog(EventTs);
CREATE INDEX IX_TrnAudit_Actor ON TblTrnRBACAuditLog(ActorUserUno);
CREATE INDEX IX_TrnAudit_Entity ON TblTrnRBACAuditLog(EntityTypeCd, EntityPk);

-- ============================================================
-- 3) HELPER VIEW
-- ============================================================
-- Effective user actions from:
--   a) Direct user-role permission
--   b) Group-role permission
--   c) Direct group permission
CREATE OR REPLACE VIEW VRBACEffectiveUserAction AS
SELECT DISTINCT
    U.UserUno,
    P.ActionUno,
    'USER_ROLE' AS SourceType
FROM TblMstRBACUser U
JOIN TblTrnRBACUserRole UR
  ON UR.UserUno = U.UserUno
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCd = 'ROLE'
 AND P.RoleUno = UR.RoleUno
WHERE U.IsActive = 1
  AND U.DeletedOn IS NULL
  AND UR.IsActive = 1
  AND UR.DeletedOn IS NULL
  AND P.IsActive = 1
  AND P.DeletedOn IS NULL
  AND P.GrantFlag = 'Y'
  AND (UR.ValidTo IS NULL OR UR.ValidTo >= TRUNC(SYSDATE))

UNION ALL

SELECT DISTINCT
    GM.UserUno,
    P.ActionUno,
    'GROUP_ROLE' AS SourceType
FROM TblTrnRBACGroupMembership GM
JOIN TblTrnRBACGroupRole GR
  ON GR.UserGroupUno = GM.UserGroupUno
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCd = 'ROLE'
 AND P.RoleUno = GR.RoleUno
WHERE GM.IsActive = 1
  AND GM.DeletedOn IS NULL
  AND GR.IsActive = 1
  AND GR.DeletedOn IS NULL
  AND P.IsActive = 1
  AND P.DeletedOn IS NULL
  AND P.GrantFlag = 'Y'
  AND (GM.ValidTo IS NULL OR GM.ValidTo >= TRUNC(SYSDATE))

UNION ALL

SELECT DISTINCT
    GM.UserUno,
    P.ActionUno,
    'GROUP_PERMISSION' AS SourceType
FROM TblTrnRBACGroupMembership GM
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCd = 'GROUP'
 AND P.UserGroupUno = GM.UserGroupUno
WHERE GM.IsActive = 1
  AND GM.DeletedOn IS NULL
  AND P.IsActive = 1
  AND P.DeletedOn IS NULL
  AND P.GrantFlag = 'Y'
  AND (GM.ValidTo IS NULL OR GM.ValidTo >= TRUNC(SYSDATE));

-- End of schema
