-- RBAC Admin Portal schema for Oracle Database
-- Naming convention requested:
--   * Master tables      : TblMstRBAC...
--   * Transaction tables : TblTrnRBAC...
--   * Primary key names  : ...Uno (RoleUno, UserUno, PermissionUno, etc.)
--   * All primary keys are identity columns.

-- ============================================================
-- 1) MASTER TABLES (TblMstRBAC*)
-- ============================================================

CREATE TABLE TblMstRBACCompany (
    CompanyUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyCode         VARCHAR2(30) NOT NULL,
    CompanyName         VARCHAR2(120) NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstRBACCompany_Code UNIQUE (CompanyCode),
    CONSTRAINT CK_MstRBACCompany_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE', 'DRAFT'))
);

CREATE TABLE TblMstRBACDepartment (
    DepartmentUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyUno          NUMBER NOT NULL,
    DepartmentCode      VARCHAR2(30) NOT NULL,
    DepartmentName      VARCHAR2(120) NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT FK_MstRBACDept_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT UQ_MstRBACDept_CompCode UNIQUE (CompanyUno, DepartmentCode),
    CONSTRAINT CK_MstRBACDept_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IX_MstRBACDept_Company ON TblMstRBACDepartment(CompanyUno);

CREATE TABLE TblMstRBACCountry (
    CountryUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Iso2Code            CHAR(2) NOT NULL,
    CountryName         VARCHAR2(120) NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT UQ_MstRBACCountry_Iso2 UNIQUE (Iso2Code),
    CONSTRAINT UQ_MstRBACCountry_Name UNIQUE (CountryName),
    CONSTRAINT CK_MstRBACCountry_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE TblMstRBACEmbassy (
    EmbassyUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CountryUno          NUMBER NOT NULL,
    EmbassyCode         VARCHAR2(40) NOT NULL,
    EmbassyName         VARCHAR2(200) NOT NULL,
    EmbassyTypeCd       VARCHAR2(30) DEFAULT 'EMBASSY' NOT NULL,
    CityName            VARCHAR2(120),
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT FK_MstRBACEmbassy_Country FOREIGN KEY (CountryUno) REFERENCES TblMstRBACCountry(CountryUno),
    CONSTRAINT UQ_MstRBACEmbassy_Code UNIQUE (EmbassyCode),
    CONSTRAINT UQ_MstRBACEmbassy_CountryName UNIQUE (CountryUno, EmbassyName),
    CONSTRAINT CK_MstRBACEmbassy_Type CHECK (EmbassyTypeCd IN ('EMBASSY', 'CONSULATE', 'HIGH_COMMISSION', 'OTHER')),
    CONSTRAINT CK_MstRBACEmbassy_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IX_MstRBACEmbassy_Country ON TblMstRBACEmbassy(CountryUno);

CREATE TABLE TblMstRBACModule (
    ModuleUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleCode          VARCHAR2(30) NOT NULL,
    ModuleName          VARCHAR2(120) NOT NULL,
    IconName            VARCHAR2(20),
    DescriptionTxt      VARCHAR2(1000),
    SortOrder           NUMBER(6) DEFAULT 0 NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstRBACModule_Code UNIQUE (ModuleCode),
    CONSTRAINT UQ_MstRBACModule_Name UNIQUE (ModuleName),
    CONSTRAINT CK_MstRBACModule_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE TblMstRBACPage (
    PageUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleUno           NUMBER NOT NULL,
    PageCode            VARCHAR2(40) NOT NULL,
    PageName            VARCHAR2(150) NOT NULL,
    RoutePath           VARCHAR2(300),
    DescriptionTxt      VARCHAR2(1000),
    SortOrder           NUMBER(6) DEFAULT 0 NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT FK_MstRBACPage_Module FOREIGN KEY (ModuleUno) REFERENCES TblMstRBACModule(ModuleUno),
    CONSTRAINT UQ_MstRBACPage_Code UNIQUE (PageCode),
    CONSTRAINT UQ_MstRBACPage_ModuleName UNIQUE (ModuleUno, PageName),
    CONSTRAINT CK_MstRBACPage_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IX_MstRBACPage_Module ON TblMstRBACPage(ModuleUno);

CREATE TABLE TblMstRBACAction (
    ActionUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PageUno             NUMBER NOT NULL,
    ActionCode          VARCHAR2(60) NOT NULL,
    ActionName          VARCHAR2(150) NOT NULL,
    ActionTypeCd        VARCHAR2(20) NOT NULL,
    DescriptionTxt      VARCHAR2(1000),
    SortOrder           NUMBER(6) DEFAULT 0 NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT FK_MstRBACAction_Page FOREIGN KEY (PageUno) REFERENCES TblMstRBACPage(PageUno),
    CONSTRAINT UQ_MstRBACAction_Code UNIQUE (ActionCode),
    CONSTRAINT UQ_MstRBACAction_PageType UNIQUE (PageUno, ActionTypeCd),
    CONSTRAINT CK_MstRBACAction_Type CHECK (ActionTypeCd IN ('VIEW', 'ADD', 'EDIT', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'CUSTOM')),
    CONSTRAINT CK_MstRBACAction_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IX_MstRBACAction_Page ON TblMstRBACAction(PageUno);

CREATE TABLE TblMstRBACRole (
    RoleUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleCode            VARCHAR2(40) NOT NULL,
    RoleName            VARCHAR2(150) NOT NULL,
    DescriptionTxt      VARCHAR2(1000),
    AccessModelCd       VARCHAR2(20) DEFAULT 'USER_LINKED' NOT NULL,
    ScopeLevelCd        VARCHAR2(20) DEFAULT 'GLOBAL' NOT NULL,
    IsSystemRole        CHAR(1) DEFAULT 'N' NOT NULL,
    IsSuperAdminRole    CHAR(1) DEFAULT 'N' NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstRBACRole_Code UNIQUE (RoleCode),
    CONSTRAINT UQ_MstRBACRole_Name UNIQUE (RoleName),
    CONSTRAINT CK_MstRBACRole_AccessModel CHECK (AccessModelCd IN ('USER_LINKED', 'GEO_SCOPED', 'GROUP_LINKED')),
    CONSTRAINT CK_MstRBACRole_ScopeLevel CHECK (ScopeLevelCd IN ('GLOBAL', 'COUNTRY', 'EMBASSY')),
    CONSTRAINT CK_MstRBACRole_IsSystem CHECK (IsSystemRole IN ('Y', 'N')),
    CONSTRAINT CK_MstRBACRole_IsSuper CHECK (IsSuperAdminRole IN ('Y', 'N')),
    CONSTRAINT CK_MstRBACRole_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE', 'DRAFT'))
);

CREATE INDEX IX_MstRBACRole_AccessModel ON TblMstRBACRole(AccessModelCd);

CREATE TABLE TblMstRBACUser (
    UserUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeId          VARCHAR2(40) NOT NULL,
    FirstName           VARCHAR2(80) NOT NULL,
    LastName            VARCHAR2(80) NOT NULL,
    EmailAddr           VARCHAR2(255) NOT NULL,
    Designation         VARCHAR2(120),
    CompanyUno          NUMBER,
    DepartmentUno       NUMBER,
    ExternalSubjectId   VARCHAR2(200),
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT UQ_MstRBACUser_Emp UNIQUE (EmployeeId),
    CONSTRAINT UQ_MstRBACUser_Email UNIQUE (EmailAddr),
    CONSTRAINT FK_MstRBACUser_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT FK_MstRBACUser_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstRBACDepartment(DepartmentUno),
    CONSTRAINT CK_MstRBACUser_Status CHECK (StatusCd IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE INDEX IX_MstRBACUser_Company ON TblMstRBACUser(CompanyUno);
CREATE INDEX IX_MstRBACUser_Department ON TblMstRBACUser(DepartmentUno);

CREATE TABLE TblMstRBACUserGroup (
    UserGroupUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyUno          NUMBER NOT NULL,
    GroupCode           VARCHAR2(50),
    GroupName           VARCHAR2(150) NOT NULL,
    GroupTypeCd         VARCHAR2(30) NOT NULL,
    DescriptionTxt      VARCHAR2(1000),
    RoleTemplateUno     NUMBER,
    EstimatedMembers    NUMBER(8),
    MembershipSourceCd  VARCHAR2(30) DEFAULT 'ORG_CHART' NOT NULL,
    StatusCd            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    UpdatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedBy           VARCHAR2(128),
    CONSTRAINT FK_MstRBACUserGroup_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT FK_MstUG_RoleTpl FOREIGN KEY (RoleTemplateUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_MstRBACUserGroup_CompName UNIQUE (CompanyUno, GroupName),
    CONSTRAINT UQ_MstRBACUserGroup_Code UNIQUE (GroupCode),
    CONSTRAINT CK_MstRBACUserGroup_Type CHECK (GroupTypeCd IN ('DEPARTMENT_TEAM', 'PUBLIC_GROUP', 'EXTERNAL_PARTNER')),
    CONSTRAINT CK_MstRBACUserGroup_Source CHECK (MembershipSourceCd IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL', 'PUBLIC')),
    CONSTRAINT CK_MstRBACUserGroup_Status CHECK (StatusCd IN ('ACTIVE', 'DRAFT', 'INACTIVE'))
);

CREATE INDEX IX_MstRBACUserGroup_Company ON TblMstRBACUserGroup(CompanyUno);

-- ============================================================
-- 2) TRANSACTION TABLES (TblTrnRBAC*)
-- ============================================================

-- Role scope (geo)
CREATE TABLE TblTrnRBACRoleCountryScope (
    RoleCountryScopeUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleUno             NUMBER NOT NULL,
    CountryUno          NUMBER NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnRoleCtry_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRoleCtry_Country FOREIGN KEY (CountryUno) REFERENCES TblMstRBACCountry(CountryUno),
    CONSTRAINT UQ_TrnRBACRoleCountryScope UNIQUE (RoleUno, CountryUno)
);

CREATE INDEX IX_TrnRoleCtry_Country ON TblTrnRBACRoleCountryScope(CountryUno);

CREATE TABLE TblTrnRBACRoleEmbassyScope (
    RoleEmbassyScopeUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleUno             NUMBER NOT NULL,
    EmbassyUno          NUMBER NOT NULL,
    CreatedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnRBACRoleEmbScope_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRBACRoleEmbScope_Embassy FOREIGN KEY (EmbassyUno) REFERENCES TblMstRBACEmbassy(EmbassyUno),
    CONSTRAINT UQ_TrnRBACRoleEmbScope UNIQUE (RoleUno, EmbassyUno)
);

CREATE INDEX IX_TrnRBACRoleEmbScope_Embassy ON TblTrnRBACRoleEmbassyScope(EmbassyUno);

-- Individual user-role assignment
CREATE TABLE TblTrnRBACUserRole (
    UserRoleUno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno             NUMBER NOT NULL,
    RoleUno             NUMBER NOT NULL,
    ValidFrom           DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    ValidTo             DATE,
    AssignedReason      VARCHAR2(500),
    AssignedAt          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    AssignedBy          VARCHAR2(128),
    CONSTRAINT FK_TrnRBACUserRole_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnRBACUserRole_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_TrnRBACUserRole UNIQUE (UserUno, RoleUno),
    CONSTRAINT CK_TrnRBACUserRole_Dates CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom)
);

CREATE INDEX IX_TrnRBACUserRole_Role ON TblTrnRBACUserRole(RoleUno);

-- Group memberships (sync from org chart/directory if required)
CREATE TABLE TblTrnRBACGroupMembership (
    GroupMembershipUno  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserGroupUno        NUMBER NOT NULL,
    UserUno             NUMBER NOT NULL,
    MembershipSourceCd  VARCHAR2(30) DEFAULT 'ORG_CHART' NOT NULL,
    ValidFrom           DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    ValidTo             DATE,
    CONSTRAINT FK_TrnRBACGroupMem_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnRBACGroupMem_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT UQ_TrnRBACGroupMembership UNIQUE (UserGroupUno, UserUno),
    CONSTRAINT CK_TrnRBACGroupMem_Source CHECK (MembershipSourceCd IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL')),
    CONSTRAINT CK_TrnRBACGroupMem_Dates CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom)
);

CREATE INDEX IX_TrnRBACGroupMem_User ON TblTrnRBACGroupMembership(UserUno);

-- Group-to-role linkage
CREATE TABLE TblTrnRBACGroupRole (
    GroupRoleUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserGroupUno        NUMBER NOT NULL,
    RoleUno             NUMBER NOT NULL,
    AssignedAt          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    AssignedBy          VARCHAR2(128),
    CONSTRAINT FK_TrnRBACGroupRole_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnRBACGroupRole_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_TrnRBACGroupRole UNIQUE (UserGroupUno, RoleUno)
);

CREATE INDEX IX_TrnRBACGroupRole_Role ON TblTrnRBACGroupRole(RoleUno);

-- Permission grants:
-- GranteeTypeCd='ROLE'  => RoleUno is used
-- GranteeTypeCd='GROUP' => UserGroupUno is used
CREATE TABLE TblTrnRBACPermission (
    PermissionUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GranteeTypeCd       VARCHAR2(20) NOT NULL,
    RoleUno             NUMBER,
    UserGroupUno        NUMBER,
    ActionUno           NUMBER NOT NULL,
    GrantFlag           CHAR(1) DEFAULT 'Y' NOT NULL,
    GrantedAt           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    GrantedBy           VARCHAR2(128),
    CONSTRAINT FK_TrnRBACPerm_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRBACPerm_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnRBACPerm_Action FOREIGN KEY (ActionUno) REFERENCES TblMstRBACAction(ActionUno),
    CONSTRAINT CK_TrnRBACPerm_GranteeType CHECK (GranteeTypeCd IN ('ROLE', 'GROUP')),
    CONSTRAINT CK_TrnRBACPerm_GrantFlag CHECK (GrantFlag IN ('Y', 'N')),
    CONSTRAINT CK_TrnRBACPerm_GranteeRef CHECK (
        (GranteeTypeCd = 'ROLE' AND RoleUno IS NOT NULL AND UserGroupUno IS NULL) OR
        (GranteeTypeCd = 'GROUP' AND UserGroupUno IS NOT NULL AND RoleUno IS NULL)
    ),
    CONSTRAINT UQ_TrnRBACPermission UNIQUE (GranteeTypeCd, RoleUno, UserGroupUno, ActionUno)
);

CREATE INDEX IX_TrnRBACPermission_Action ON TblTrnRBACPermission(ActionUno);
CREATE INDEX IX_TrnRBACPermission_Role ON TblTrnRBACPermission(RoleUno);
CREATE INDEX IX_TrnRBACPermission_Group ON TblTrnRBACPermission(UserGroupUno);

CREATE TABLE TblTrnRBACAuditLog (
    AuditUno            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EventTs             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ActorUserUno        NUMBER,
    EventTypeCd         VARCHAR2(60) NOT NULL,
    EntityTypeCd        VARCHAR2(60) NOT NULL,
    EntityPk            VARCHAR2(120),
    DetailJson          CLOB,
    IpAddress           VARCHAR2(64),
    UserAgent           VARCHAR2(1000),
    CONSTRAINT FK_TrnRBACAudit_Actor FOREIGN KEY (ActorUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnRBACAudit_Json CHECK (DetailJson IS JSON)
);

CREATE INDEX IX_TrnRBACAudit_EventTs ON TblTrnRBACAuditLog(EventTs);
CREATE INDEX IX_TrnRBACAudit_Actor ON TblTrnRBACAuditLog(ActorUserUno);
CREATE INDEX IX_TrnRBACAudit_Entity ON TblTrnRBACAuditLog(EntityTypeCd, EntityPk);

-- ============================================================
-- 3) HELPER VIEW
-- ============================================================
-- Effective user actions from:
--   a) Direct user-role permission
--   b) Group-role permission
--   c) Direct group permission
CREATE OR REPLACE VIEW VRBACEffectiveUserAction AS
SELECT DISTINCT
    U.UserUno,
    P.ActionUno,
    'USER_ROLE' AS SourceType
FROM TblMstRBACUser U
JOIN TblTrnRBACUserRole UR
  ON UR.UserUno = U.UserUno
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCd = 'ROLE'
 AND P.RoleUno = UR.RoleUno
WHERE P.GrantFlag = 'Y'
  AND (UR.ValidTo IS NULL OR UR.ValidTo >= TRUNC(SYSDATE))

UNION ALL

SELECT DISTINCT
    GM.UserUno,
    P.ActionUno,
    'GROUP_ROLE' AS SourceType
FROM TblTrnRBACGroupMembership GM
JOIN TblTrnRBACGroupRole GR
  ON GR.UserGroupUno = GM.UserGroupUno
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCd = 'ROLE'
 AND P.RoleUno = GR.RoleUno
WHERE P.GrantFlag = 'Y'
  AND (GM.ValidTo IS NULL OR GM.ValidTo >= TRUNC(SYSDATE))

UNION ALL

SELECT DISTINCT
    GM.UserUno,
    P.ActionUno,
    'GROUP_PERMISSION' AS SourceType
FROM TblTrnRBACGroupMembership GM
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCd = 'GROUP'
 AND P.UserGroupUno = GM.UserGroupUno
WHERE P.GrantFlag = 'Y'
  AND (GM.ValidTo IS NULL OR GM.ValidTo >= TRUNC(SYSDATE));

-- End of schema
