-- ITIL Service Desk schema for Oracle Database
-- Naming convention aligned with Admin Portal table design:
--   * Master tables      : TblMstSD...
--   * Transaction tables : TblTrnSD...
--   * Primary key names  : ...Uno
--   * Identity PK on all tables
--   * IsActive NUMBER(1) in all tables
--   * Audit fields: EnteredOn/By, ModifiedOn/By, DeletedOn/By

-- ============================================================
-- 1) MASTER TABLES (TblMstSD*)
-- ============================================================

CREATE TABLE TblMstSDSupportLevel (
    SupportLevelUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupportLevelCode      VARCHAR2(20) NOT NULL,  -- SUPPORT_TEAM, L1, L2, L3, MANAGER
    SupportLevelNameEn    VARCHAR2(120) NOT NULL,
    SupportLevelNameAr    NVARCHAR2(120),
    LevelSortOrder        NUMBER(3) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDSupportLevel_Code UNIQUE (SupportLevelCode),
    CONSTRAINT CK_MstSDSupportLevel_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDDepartment (
    DepartmentUno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DepartmentCode        VARCHAR2(40) NOT NULL,
    DepartmentNameEn      VARCHAR2(150) NOT NULL,
    DepartmentNameAr      NVARCHAR2(150),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDDepartment_Code UNIQUE (DepartmentCode),
    CONSTRAINT CK_MstSDDepartment_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDSection (
    SectionUno            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DepartmentUno         NUMBER NOT NULL,
    SectionCode           VARCHAR2(40) NOT NULL,
    SectionNameEn         VARCHAR2(150) NOT NULL,
    SectionNameAr         NVARCHAR2(150),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDSection_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstSDDepartment(DepartmentUno),
    CONSTRAINT UQ_MstSDSection_Code UNIQUE (SectionCode),
    CONSTRAINT UQ_MstSDSection_DeptSec UNIQUE (DepartmentUno, SectionNameEn),
    CONSTRAINT CK_MstSDSection_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_MstSDSection_Department ON TblMstSDSection(DepartmentUno);

CREATE TABLE TblMstSDTeam (
    TeamUno               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TeamCode              VARCHAR2(40) NOT NULL,
    TeamNameEn            VARCHAR2(150) NOT NULL,
    TeamNameAr            NVARCHAR2(150),
    SupportLevelUno       NUMBER NOT NULL,
    DepartmentUno         NUMBER,
    SectionUno            NUMBER,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDTeam_Level FOREIGN KEY (SupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_MstSDTeam_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstSDDepartment(DepartmentUno),
    CONSTRAINT FK_MstSDTeam_Section FOREIGN KEY (SectionUno) REFERENCES TblMstSDSection(SectionUno),
    CONSTRAINT UQ_MstSDTeam_Code UNIQUE (TeamCode),
    CONSTRAINT CK_MstSDTeam_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_MstSDTeam_Level ON TblMstSDTeam(SupportLevelUno);
CREATE INDEX IX_MstSDTeam_Department ON TblMstSDTeam(DepartmentUno);
CREATE INDEX IX_MstSDTeam_Section ON TblMstSDTeam(SectionUno);

CREATE TABLE TblMstSDUser (
    UserUno               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeNo            VARCHAR2(40),
    UserName              VARCHAR2(120) NOT NULL,
    DisplayNameEn         VARCHAR2(200) NOT NULL,
    DisplayNameAr         NVARCHAR2(200),
    EmailAddress          VARCHAR2(320),
    SupportLevelUno       NUMBER,
    TeamUno               NUMBER,
    DepartmentUno         NUMBER,
    SectionUno            NUMBER,
    IsAgent               NUMBER(1) DEFAULT 0 NOT NULL,
    IsAvailable           NUMBER(1) DEFAULT 1 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDUser_Level FOREIGN KEY (SupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_MstSDUser_Team FOREIGN KEY (TeamUno) REFERENCES TblMstSDTeam(TeamUno),
    CONSTRAINT FK_MstSDUser_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstSDDepartment(DepartmentUno),
    CONSTRAINT FK_MstSDUser_Section FOREIGN KEY (SectionUno) REFERENCES TblMstSDSection(SectionUno),
    CONSTRAINT UQ_MstSDUser_UserName UNIQUE (UserName),
    CONSTRAINT UQ_MstSDUser_Email UNIQUE (EmailAddress),
    CONSTRAINT CK_MstSDUser_IsAgent CHECK (IsAgent IN (0,1)),
    CONSTRAINT CK_MstSDUser_IsAvailable CHECK (IsAvailable IN (0,1)),
    CONSTRAINT CK_MstSDUser_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDTicketType (
    TicketTypeUno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketTypeCode        VARCHAR2(30) NOT NULL,  -- INCIDENT, SERVICE_REQUEST, PROBLEM, CHANGE_REQUEST
    TicketTypeNameEn      VARCHAR2(120) NOT NULL,
    TicketTypeNameAr      NVARCHAR2(120),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDTicketType_Code UNIQUE (TicketTypeCode),
    CONSTRAINT CK_MstSDTicketType_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDTicketStatus (
    TicketStatusUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StatusCode            VARCHAR2(40) NOT NULL,
    StatusNameEn          VARCHAR2(120) NOT NULL,
    StatusNameAr          NVARCHAR2(120),
    TicketTypeUno         NUMBER,
    IsTerminal            NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDStatus_Type FOREIGN KEY (TicketTypeUno) REFERENCES TblMstSDTicketType(TicketTypeUno),
    CONSTRAINT UQ_MstSDStatus_Code UNIQUE (StatusCode),
    CONSTRAINT CK_MstSDStatus_IsTerminal CHECK (IsTerminal IN (0,1)),
    CONSTRAINT CK_MstSDStatus_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDImpact (
    ImpactUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ImpactCode            VARCHAR2(20) NOT NULL, -- HIGH, MEDIUM, LOW
    ImpactNameEn          VARCHAR2(80) NOT NULL,
    ImpactNameAr          NVARCHAR2(80),
    SortOrder             NUMBER(3) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDImpact_Code UNIQUE (ImpactCode),
    CONSTRAINT CK_MstSDImpact_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDUrgency (
    UrgencyUno            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UrgencyCode           VARCHAR2(20) NOT NULL, -- HIGH, MEDIUM, LOW
    UrgencyNameEn         VARCHAR2(80) NOT NULL,
    UrgencyNameAr         NVARCHAR2(80),
    SortOrder             NUMBER(3) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDUrgency_Code UNIQUE (UrgencyCode),
    CONSTRAINT CK_MstSDUrgency_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDPriority (
    PriorityUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PriorityCode          VARCHAR2(10) NOT NULL,   -- P1, P2, P3, P4
    PriorityNameEn        VARCHAR2(80) NOT NULL,   -- Critical, High...
    PriorityNameAr        NVARCHAR2(80),
    ResponseSlaHours      NUMBER(5,2) NOT NULL,
    ResolutionSlaHours    NUMBER(6,2),
    SortOrder             NUMBER(3) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDPriority_Code UNIQUE (PriorityCode),
    CONSTRAINT CK_MstSDPriority_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDPriorityMatrix (
    PriorityMatrixUno     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ImpactUno             NUMBER NOT NULL,
    UrgencyUno            NUMBER NOT NULL,
    PriorityUno           NUMBER NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDPrioMatrix_Impact FOREIGN KEY (ImpactUno) REFERENCES TblMstSDImpact(ImpactUno),
    CONSTRAINT FK_MstSDPrioMatrix_Urgency FOREIGN KEY (UrgencyUno) REFERENCES TblMstSDUrgency(UrgencyUno),
    CONSTRAINT FK_MstSDPrioMatrix_Priority FOREIGN KEY (PriorityUno) REFERENCES TblMstSDPriority(PriorityUno),
    CONSTRAINT UQ_MstSDPrioMatrix_IU UNIQUE (ImpactUno, UrgencyUno),
    CONSTRAINT CK_MstSDPrioMatrix_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDCategory (
    CategoryUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryCode          VARCHAR2(40) NOT NULL,
    CategoryNameEn        VARCHAR2(120) NOT NULL,
    CategoryNameAr        NVARCHAR2(120),
    TicketTypeUno         NUMBER,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDCategory_Type FOREIGN KEY (TicketTypeUno) REFERENCES TblMstSDTicketType(TicketTypeUno),
    CONSTRAINT UQ_MstSDCategory_Code UNIQUE (CategoryCode),
    CONSTRAINT CK_MstSDCategory_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDSubType (
    SubTypeUno            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketTypeUno         NUMBER NOT NULL,
    SubTypeCode           VARCHAR2(50) NOT NULL,
    SubTypeNameEn         VARCHAR2(150) NOT NULL,
    SubTypeNameAr         NVARCHAR2(150),
    CategoryUno           NUMBER,
    DefaultImpactUno      NUMBER,
    DefaultUrgencyUno     NUMBER,
    ChangeTypeCode        VARCHAR2(20), -- STANDARD, NORMAL, EMERGENCY
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDSubType_Type FOREIGN KEY (TicketTypeUno) REFERENCES TblMstSDTicketType(TicketTypeUno),
    CONSTRAINT FK_MstSDSubType_Category FOREIGN KEY (CategoryUno) REFERENCES TblMstSDCategory(CategoryUno),
    CONSTRAINT FK_MstSDSubType_Impact FOREIGN KEY (DefaultImpactUno) REFERENCES TblMstSDImpact(ImpactUno),
    CONSTRAINT FK_MstSDSubType_Urgency FOREIGN KEY (DefaultUrgencyUno) REFERENCES TblMstSDUrgency(UrgencyUno),
    CONSTRAINT UQ_MstSDSubType_TypeCode UNIQUE (TicketTypeUno, SubTypeCode),
    CONSTRAINT CK_MstSDSubType_ChangeType CHECK (ChangeTypeCode IN ('STANDARD','NORMAL','EMERGENCY') OR ChangeTypeCode IS NULL),
    CONSTRAINT CK_MstSDSubType_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDChannel (
    ChannelUno            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ChannelCode           VARCHAR2(40) NOT NULL,
    ChannelNameEn         VARCHAR2(120) NOT NULL,
    ChannelNameAr         NVARCHAR2(120),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDChannel_Code UNIQUE (ChannelCode),
    CONSTRAINT CK_MstSDChannel_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDAffectedService (
    AffectedServiceUno    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceCode           VARCHAR2(60) NOT NULL,
    ServiceNameEn         VARCHAR2(200) NOT NULL,
    ServiceNameAr         NVARCHAR2(200),
    OwnerTeamUno          NUMBER,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDAffectedService_Team FOREIGN KEY (OwnerTeamUno) REFERENCES TblMstSDTeam(TeamUno),
    CONSTRAINT UQ_MstSDAffectedService_Code UNIQUE (ServiceCode),
    CONSTRAINT CK_MstSDAffectedService_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDSourceSystem (
    SourceSystemUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SourceSystemCode      VARCHAR2(40) NOT NULL,  -- CRM, CALL_CENTER, SUPPORT_CENTER, CUSTOMER_APP, ADMIN_APP, GRC_APP
    SourceSystemNameEn    VARCHAR2(120) NOT NULL,
    SourceSystemNameAr    NVARCHAR2(120),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDSourceSystem_Code UNIQUE (SourceSystemCode),
    CONSTRAINT CK_MstSDSourceSystem_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDCABGroup (
    CABGroupUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CABGroupCode          VARCHAR2(40) NOT NULL,
    CABGroupNameEn        VARCHAR2(120) NOT NULL,
    CABGroupNameAr        NVARCHAR2(120),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDCABGroup_Code UNIQUE (CABGroupCode),
    CONSTRAINT CK_MstSDCABGroup_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDKBTag (
    KBTagUno              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KBTagCode             VARCHAR2(50) NOT NULL,
    KBTagNameEn           VARCHAR2(120) NOT NULL,
    KBTagNameAr           NVARCHAR2(120),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDKBTag_Code UNIQUE (KBTagCode),
    CONSTRAINT CK_MstSDKBTag_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDCatalogItem (
    CatalogItemUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CatalogItemCode       VARCHAR2(40) NOT NULL,
    ItemNameEn            VARCHAR2(200) NOT NULL,
    ItemNameAr            NVARCHAR2(200),
    CategoryUno           NUMBER,
    DefaultSubTypeUno     NUMBER,
    ApprovalRequired      NUMBER(1) DEFAULT 0 NOT NULL,
    DefaultSlaHours       NUMBER(6,2),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDCatalogItem_Category FOREIGN KEY (CategoryUno) REFERENCES TblMstSDCategory(CategoryUno),
    CONSTRAINT FK_MstSDCatalogItem_SubType FOREIGN KEY (DefaultSubTypeUno) REFERENCES TblMstSDSubType(SubTypeUno),
    CONSTRAINT UQ_MstSDCatalogItem_Code UNIQUE (CatalogItemCode),
    CONSTRAINT CK_MstSDCatalogItem_Approval CHECK (ApprovalRequired IN (0,1)),
    CONSTRAINT CK_MstSDCatalogItem_IsActive CHECK (IsActive IN (0,1))
);

-- ============================================================
-- 2) TRANSACTION TABLES (TblTrnSD*)
-- ============================================================

CREATE TABLE TblTrnSDSourceTransaction (
    SourceTxnUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SourceSystemUno       NUMBER NOT NULL,
    SourceTxnRefNo        VARCHAR2(120) NOT NULL,
    SourceTxnTypeCode     VARCHAR2(50),
    SourceTxnDate         TIMESTAMP(6),
    SourcePayloadJson     CLOB,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDSourceTxn_System FOREIGN KEY (SourceSystemUno) REFERENCES TblMstSDSourceSystem(SourceSystemUno),
    CONSTRAINT UQ_TrnSDSourceTxn_SystemRef UNIQUE (SourceSystemUno, SourceTxnRefNo),
    CONSTRAINT CK_TrnSDSourceTxn_IsActive CHECK (IsActive IN (0,1)),
    CONSTRAINT CK_TrnSDSourceTxn_Json CHECK (SourcePayloadJson IS JSON)
);

CREATE TABLE TblTrnSDTicket (
    TicketUno             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketNo              VARCHAR2(30) NOT NULL,     -- INC-0001 / SR-0001 / PRB-0001 / CHG-0001
    TicketTypeUno         NUMBER NOT NULL,
    TicketStatusUno       NUMBER NOT NULL,
    Title                 VARCHAR2(500) NOT NULL,
    Description           CLOB,
    SubTypeUno            NUMBER,
    CategoryUno           NUMBER,
    ChannelUno            NUMBER,
    AffectedServiceUno    NUMBER,
    ImpactUno             NUMBER,
    UrgencyUno            NUMBER,
    PriorityUno           NUMBER,
    CurrentSupportLevelUno NUMBER,
    CurrentTeamUno        NUMBER,
    SubmittedByUserUno    NUMBER NOT NULL,
    RequesterDepartmentUno NUMBER,
    RequesterSectionUno   NUMBER,
    AssignedToUserUno     NUMBER,
    ReferenceNo           VARCHAR2(120),             -- line item / external reference
    IsAutoClose           NUMBER(1) DEFAULT 0 NOT NULL,
    CreatedOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FirstResponseOn       TIMESTAMP(6),
    ResponseSlaDueOn      TIMESTAMP(6),
    ResolutionSlaDueOn    TIMESTAMP(6),
    FirstBreachedOn       TIMESTAMP(6),
    ResolvedOn            TIMESTAMP(6),
    ClosedOn              TIMESTAMP(6),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDTicket_Type FOREIGN KEY (TicketTypeUno) REFERENCES TblMstSDTicketType(TicketTypeUno),
    CONSTRAINT FK_TrnSDTicket_Status FOREIGN KEY (TicketStatusUno) REFERENCES TblMstSDTicketStatus(TicketStatusUno),
    CONSTRAINT FK_TrnSDTicket_SubType FOREIGN KEY (SubTypeUno) REFERENCES TblMstSDSubType(SubTypeUno),
    CONSTRAINT FK_TrnSDTicket_Category FOREIGN KEY (CategoryUno) REFERENCES TblMstSDCategory(CategoryUno),
    CONSTRAINT FK_TrnSDTicket_Channel FOREIGN KEY (ChannelUno) REFERENCES TblMstSDChannel(ChannelUno),
    CONSTRAINT FK_TrnSDTicket_Service FOREIGN KEY (AffectedServiceUno) REFERENCES TblMstSDAffectedService(AffectedServiceUno),
    CONSTRAINT FK_TrnSDTicket_Impact FOREIGN KEY (ImpactUno) REFERENCES TblMstSDImpact(ImpactUno),
    CONSTRAINT FK_TrnSDTicket_Urgency FOREIGN KEY (UrgencyUno) REFERENCES TblMstSDUrgency(UrgencyUno),
    CONSTRAINT FK_TrnSDTicket_Priority FOREIGN KEY (PriorityUno) REFERENCES TblMstSDPriority(PriorityUno),
    CONSTRAINT FK_TrnSDTicket_Level FOREIGN KEY (CurrentSupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_TrnSDTicket_Team FOREIGN KEY (CurrentTeamUno) REFERENCES TblMstSDTeam(TeamUno),
    CONSTRAINT FK_TrnSDTicket_SubmittedBy FOREIGN KEY (SubmittedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT FK_TrnSDTicket_ReqDept FOREIGN KEY (RequesterDepartmentUno) REFERENCES TblMstSDDepartment(DepartmentUno),
    CONSTRAINT FK_TrnSDTicket_ReqSection FOREIGN KEY (RequesterSectionUno) REFERENCES TblMstSDSection(SectionUno),
    CONSTRAINT FK_TrnSDTicket_AssignedTo FOREIGN KEY (AssignedToUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT UQ_TrnSDTicket_No UNIQUE (TicketNo),
    CONSTRAINT CK_TrnSDTicket_AutoClose CHECK (IsAutoClose IN (0,1)),
    CONSTRAINT CK_TrnSDTicket_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDTicket_AssigneeStatus ON TblTrnSDTicket(AssignedToUserUno, TicketStatusUno);
CREATE INDEX IX_TrnSDTicket_LevelPriority ON TblTrnSDTicket(CurrentSupportLevelUno, PriorityUno, CreatedOn);
CREATE INDEX IX_TrnSDTicket_ReqDept ON TblTrnSDTicket(RequesterDepartmentUno, CreatedOn);
CREATE INDEX IX_TrnSDTicket_ReqSection ON TblTrnSDTicket(RequesterSectionUno, CreatedOn);

-- One service request must be linked to exactly one source transaction.
CREATE TABLE TblTrnSDServiceRequest (
    TicketUno             NUMBER PRIMARY KEY,
    SourceTxnUno          NUMBER NOT NULL,
    CatalogItemUno        NUMBER,
    ApprovalRequired      NUMBER(1) DEFAULT 0 NOT NULL,
    ApprovalStatusCode    VARCHAR2(30) DEFAULT 'NOT_REQUIRED' NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDSR_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDSR_SourceTxn FOREIGN KEY (SourceTxnUno) REFERENCES TblTrnSDSourceTransaction(SourceTxnUno),
    CONSTRAINT FK_TrnSDSR_CatalogItem FOREIGN KEY (CatalogItemUno) REFERENCES TblMstSDCatalogItem(CatalogItemUno),
    CONSTRAINT UQ_TrnSDSR_SourceTxn UNIQUE (SourceTxnUno),
    CONSTRAINT CK_TrnSDSR_ApprovalReq CHECK (ApprovalRequired IN (0,1)),
    CONSTRAINT CK_TrnSDSR_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDProblem (
    TicketUno             NUMBER PRIMARY KEY,
    IsKnownError          NUMBER(1) DEFAULT 0 NOT NULL,
    RootCauseText         CLOB,
    WorkaroundText        CLOB,
    PermanentFixText      CLOB,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDProblem_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT CK_TrnSDProblem_KnownError CHECK (IsKnownError IN (0,1)),
    CONSTRAINT CK_TrnSDProblem_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDChangeRequest (
    TicketUno             NUMBER PRIMARY KEY,
    ChangeTypeCode        VARCHAR2(20) NOT NULL,   -- STANDARD, NORMAL, EMERGENCY
    CABRequired           NUMBER(1) DEFAULT 0 NOT NULL,
    CABStatusCode         VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, -- PENDING/APPROVED/REJECTED/PRE_APPROVED
    PlannedStartOn        TIMESTAMP(6),
    PlannedEndOn          TIMESTAMP(6),
    RiskAssessmentText    CLOB,
    RollbackPlanText      CLOB,
    CABGroupUno           NUMBER,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDChange_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDChange_CABGroup FOREIGN KEY (CABGroupUno) REFERENCES TblMstSDCABGroup(CABGroupUno),
    CONSTRAINT CK_TrnSDChange_Type CHECK (ChangeTypeCode IN ('STANDARD','NORMAL','EMERGENCY')),
    CONSTRAINT CK_TrnSDChange_CABReq CHECK (CABRequired IN (0,1)),
    CONSTRAINT CK_TrnSDChange_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDTicketAssignment (
    TicketAssignmentUno   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    AssignedFromUserUno   NUMBER,
    AssignedToUserUno     NUMBER NOT NULL,
    AssignedFromLevelUno  NUMBER,
    AssignedToLevelUno    NUMBER,
    AssignedFromTeamUno   NUMBER,
    AssignedToTeamUno     NUMBER,
    AssignmentReasonCode  VARCHAR2(40), -- AUTO_ROUND_ROBIN / MANUAL / REASSIGN / ESCALATION
    AssignedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDAssign_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDAssign_FromUser FOREIGN KEY (AssignedFromUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT FK_TrnSDAssign_ToUser FOREIGN KEY (AssignedToUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT FK_TrnSDAssign_FromLevel FOREIGN KEY (AssignedFromLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_TrnSDAssign_ToLevel FOREIGN KEY (AssignedToLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_TrnSDAssign_FromTeam FOREIGN KEY (AssignedFromTeamUno) REFERENCES TblMstSDTeam(TeamUno),
    CONSTRAINT FK_TrnSDAssign_ToTeam FOREIGN KEY (AssignedToTeamUno) REFERENCES TblMstSDTeam(TeamUno),
    CONSTRAINT CK_TrnSDAssign_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDAssign_TicketOn ON TblTrnSDTicketAssignment(TicketUno, AssignedOn);

CREATE TABLE TblTrnSDEscalation (
    EscalationUno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    FromSupportLevelUno   NUMBER,
    ToSupportLevelUno     NUMBER NOT NULL,
    EscalatedByUserUno    NUMBER,
    EscalationReasonEn    VARCHAR2(1000),
    EscalationReasonAr    NVARCHAR2(1000),
    EscalatedOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsAutoEscalation      NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDEsc_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDEsc_FromLevel FOREIGN KEY (FromSupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_TrnSDEsc_ToLevel FOREIGN KEY (ToSupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_TrnSDEsc_ByUser FOREIGN KEY (EscalatedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDEsc_Auto CHECK (IsAutoEscalation IN (0,1)),
    CONSTRAINT CK_TrnSDEsc_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDTicketWorkflow (
    TicketWorkflowUno     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    EventTypeCode         VARCHAR2(40) NOT NULL, -- CREATED, ASSIGNED, ESCALATED, UPDATED, CAB_DECISION, RESOLVED, CLOSED...
    EventDescriptionEn    VARCHAR2(2000),
    EventDescriptionAr    NVARCHAR2(2000),
    ActorUserUno          NUMBER,
    EventOn               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsInternalEvent       NUMBER(1) DEFAULT 1 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDWf_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDWf_Actor FOREIGN KEY (ActorUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDWf_Internal CHECK (IsInternalEvent IN (0,1)),
    CONSTRAINT CK_TrnSDWf_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDWf_TicketOn ON TblTrnSDTicketWorkflow(TicketUno, EventOn);

CREATE TABLE TblTrnSDTicketComment (
    TicketCommentUno      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    CommentByUserUno      NUMBER NOT NULL,
    CommentText           CLOB NOT NULL,
    IsInternalComment     NUMBER(1) DEFAULT 0 NOT NULL,
    CommentOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDComment_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDComment_ByUser FOREIGN KEY (CommentByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDComment_Internal CHECK (IsInternalComment IN (0,1)),
    CONSTRAINT CK_TrnSDComment_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDComment_TicketOn ON TblTrnSDTicketComment(TicketUno, CommentOn);

CREATE TABLE TblTrnSDTicketLink (
    TicketLinkUno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ParentTicketUno       NUMBER NOT NULL,
    ChildTicketUno        NUMBER NOT NULL,
    LinkTypeCode          VARCHAR2(40) NOT NULL, -- RELATED / CAUSED_BY / DUPLICATE_OF / PROBLEM_OF / CHANGE_OF
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDLink_Parent FOREIGN KEY (ParentTicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDLink_Child FOREIGN KEY (ChildTicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT UQ_TrnSDLink_Unique UNIQUE (ParentTicketUno, ChildTicketUno, LinkTypeCode),
    CONSTRAINT CK_TrnSDLink_NotSelf CHECK (ParentTicketUno <> ChildTicketUno),
    CONSTRAINT CK_TrnSDLink_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDCABDecision (
    CABDecisionUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    CABGroupUno           NUMBER,
    DecisionCode          VARCHAR2(20) NOT NULL, -- APPROVED / REJECTED / DEFERRED
    DecisionRemarksEn     VARCHAR2(2000),
    DecisionRemarksAr     NVARCHAR2(2000),
    DecidedByUserUno      NUMBER NOT NULL,
    DecidedOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDCAB_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDCAB_Group FOREIGN KEY (CABGroupUno) REFERENCES TblMstSDCABGroup(CABGroupUno),
    CONSTRAINT FK_TrnSDCAB_ByUser FOREIGN KEY (DecidedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDCAB_Decision CHECK (DecisionCode IN ('APPROVED','REJECTED','DEFERRED')),
    CONSTRAINT CK_TrnSDCAB_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDKBArticle (
    KBArticleUno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ArticleNo             VARCHAR2(30) NOT NULL, -- KBA-0001
    TitleEn               VARCHAR2(500) NOT NULL,
    TitleAr               NVARCHAR2(500),
    ArticleStatusCode     VARCHAR2(30) NOT NULL, -- DRAFT, PUBLISHED, KNOWN_ERROR, RETIRED
    ContentText           CLOB NOT NULL,
    HelpfulPercent        NUMBER(5,2),
    ViewCount             NUMBER DEFAULT 0 NOT NULL,
    PublishedByUserUno    NUMBER,
    PublishedOn           TIMESTAMP(6),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDKBArticle_PubBy FOREIGN KEY (PublishedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT UQ_TrnSDKBArticle_No UNIQUE (ArticleNo),
    CONSTRAINT CK_TrnSDKBArticle_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDKBArticleTag (
    KBArticleTagUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KBArticleUno          NUMBER NOT NULL,
    KBTagUno              NUMBER NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDKBAT_Article FOREIGN KEY (KBArticleUno) REFERENCES TblTrnSDKBArticle(KBArticleUno),
    CONSTRAINT FK_TrnSDKBAT_Tag FOREIGN KEY (KBTagUno) REFERENCES TblMstSDKBTag(KBTagUno),
    CONSTRAINT UQ_TrnSDKBAT_Unique UNIQUE (KBArticleUno, KBTagUno),
    CONSTRAINT CK_TrnSDKBAT_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDKBArticleTicket (
    KBArticleTicketUno    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KBArticleUno          NUMBER NOT NULL,
    TicketUno             NUMBER NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDKBATicket_Article FOREIGN KEY (KBArticleUno) REFERENCES TblTrnSDKBArticle(KBArticleUno),
    CONSTRAINT FK_TrnSDKBATicket_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT UQ_TrnSDKBATicket_Unique UNIQUE (KBArticleUno, TicketUno),
    CONSTRAINT CK_TrnSDKBATicket_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDCatalogRequest (
    CatalogRequestUno     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CatalogItemUno        NUMBER NOT NULL,
    TicketUno             NUMBER NOT NULL,
    RequestedByUserUno    NUMBER NOT NULL,
    RequestQuantity       NUMBER DEFAULT 1 NOT NULL,
    IsAutoApproved        NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDCatalogReq_Item FOREIGN KEY (CatalogItemUno) REFERENCES TblMstSDCatalogItem(CatalogItemUno),
    CONSTRAINT FK_TrnSDCatalogReq_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDCatalogReq_ByUser FOREIGN KEY (RequestedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT UQ_TrnSDCatalogReq_Ticket UNIQUE (TicketUno),
    CONSTRAINT CK_TrnSDCatalogReq_AutoApproved CHECK (IsAutoApproved IN (0,1)),
    CONSTRAINT CK_TrnSDCatalogReq_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDNotification (
    NotificationUno       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NotificationTypeCode  VARCHAR2(30) NOT NULL, -- ALERT / ASSIGNED / INFO
    TitleEn               VARCHAR2(500) NOT NULL,
    TitleAr               NVARCHAR2(500),
    MessageEn             VARCHAR2(2000),
    MessageAr             NVARCHAR2(2000),
    TicketUno             NUMBER,
    CreatedOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDNotif_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT CK_TrnSDNotif_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDNotificationRead (
    NotificationReadUno   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NotificationUno       NUMBER NOT NULL,
    RecipientUserUno      NUMBER NOT NULL,
    IsRead                NUMBER(1) DEFAULT 0 NOT NULL,
    ReadOn                TIMESTAMP(6),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDNotifRead_Notification FOREIGN KEY (NotificationUno) REFERENCES TblTrnSDNotification(NotificationUno),
    CONSTRAINT FK_TrnSDNotifRead_User FOREIGN KEY (RecipientUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT UQ_TrnSDNotifRead_Unique UNIQUE (NotificationUno, RecipientUserUno),
    CONSTRAINT CK_TrnSDNotifRead_IsRead CHECK (IsRead IN (0,1)),
    CONSTRAINT CK_TrnSDNotifRead_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDSLAEvent (
    SLAEventUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    SLAEventTypeCode      VARCHAR2(30) NOT NULL, -- WARNING, BREACH, PAUSED, RESUMED, MET
    SLAThresholdPercent   NUMBER(5,2),
    EventOn               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EventRemarkEn         VARCHAR2(1000),
    EventRemarkAr         NVARCHAR2(1000),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDSLAEvent_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT CK_TrnSDSLAEvent_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDSLAEvent_TicketOn ON TblTrnSDSLAEvent(TicketUno, EventOn);

-- Auto escalation rules by level/priority/ticket type
CREATE TABLE TblMstSDAutoEscalationRule (
    AutoEscalationRuleUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RuleCode              VARCHAR2(50) NOT NULL,
    RuleNameEn            VARCHAR2(200) NOT NULL,
    RuleNameAr            NVARCHAR2(200),
    TicketTypeUno         NUMBER,
    PriorityUno           NUMBER,
    FromSupportLevelUno   NUMBER,
    ToSupportLevelUno     NUMBER NOT NULL,
    TriggerPercentSla     NUMBER(5,2), -- e.g. 75 or 100
    TriggerAfterMinutes   NUMBER,      -- fixed minute trigger, optional
    IsAutoEscalate        NUMBER(1) DEFAULT 1 NOT NULL,
    IsNotifyOnly          NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDAutoEscRule_Type FOREIGN KEY (TicketTypeUno) REFERENCES TblMstSDTicketType(TicketTypeUno),
    CONSTRAINT FK_MstSDAutoEscRule_Priority FOREIGN KEY (PriorityUno) REFERENCES TblMstSDPriority(PriorityUno),
    CONSTRAINT FK_MstSDAutoEscRule_FromLevel FOREIGN KEY (FromSupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT FK_MstSDAutoEscRule_ToLevel FOREIGN KEY (ToSupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT UQ_MstSDAutoEscRule_Code UNIQUE (RuleCode),
    CONSTRAINT CK_MstSDAutoEscRule_Auto CHECK (IsAutoEscalate IN (0,1)),
    CONSTRAINT CK_MstSDAutoEscRule_Notify CHECK (IsNotifyOnly IN (0,1)),
    CONSTRAINT CK_MstSDAutoEscRule_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDFeedbackCategory (
    FeedbackCategoryUno   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FeedbackCategoryCode  VARCHAR2(40) NOT NULL,
    FeedbackCategoryNameEn VARCHAR2(150) NOT NULL,
    FeedbackCategoryNameAr NVARCHAR2(150),
    CategoryTypeCode      VARCHAR2(20) NOT NULL, -- FEEDBACK / SUGGESTION
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT UQ_MstSDFeedbackCategory_Code UNIQUE (FeedbackCategoryCode),
    CONSTRAINT CK_MstSDFeedbackCategory_Type CHECK (CategoryTypeCode IN ('FEEDBACK','SUGGESTION')),
    CONSTRAINT CK_MstSDFeedbackCategory_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblMstSDQualityParameter (
    QualityParameterUno   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    QualityParameterCode  VARCHAR2(50) NOT NULL,
    ParameterNameEn       VARCHAR2(200) NOT NULL,
    ParameterNameAr       NVARCHAR2(200),
    AppliesToTicketTypeUno NUMBER,
    WeightPercent         NUMBER(5,2) DEFAULT 0 NOT NULL,
    IsMandatory           NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_MstSDQualityParam_Type FOREIGN KEY (AppliesToTicketTypeUno) REFERENCES TblMstSDTicketType(TicketTypeUno),
    CONSTRAINT UQ_MstSDQualityParam_Code UNIQUE (QualityParameterCode),
    CONSTRAINT CK_MstSDQualityParam_Mandatory CHECK (IsMandatory IN (0,1)),
    CONSTRAINT CK_MstSDQualityParam_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDTicketFollowUp (
    TicketFollowUpUno     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    FollowUpByUserUno     NUMBER NOT NULL,
    FollowUpTypeCode      VARCHAR2(30) NOT NULL, -- CUSTOMER_UPDATE/INTERNAL_REMINDER/CHASER/CLOSURE_CONFIRM
    FollowUpNote          VARCHAR2(2000),
    NextFollowUpOn        TIMESTAMP(6),
    FollowUpStatusCode    VARCHAR2(30) DEFAULT 'OPEN' NOT NULL, -- OPEN/COMPLETED/CANCELLED
    FollowUpOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDFollowUp_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDFollowUp_ByUser FOREIGN KEY (FollowUpByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDFollowUp_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDFollowUp_TicketOn ON TblTrnSDTicketFollowUp(TicketUno, FollowUpOn);

CREATE TABLE TblTrnSDAutoEscalationAudit (
    AutoEscalationAuditUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AutoEscalationRuleUno NUMBER NOT NULL,
    TicketUno             NUMBER NOT NULL,
    ActionCode            VARCHAR2(20) NOT NULL, -- SUGGESTED/ESCALATED/SKIPPED/FAILED
    ActionRemarkEn        VARCHAR2(1000),
    ActionRemarkAr        NVARCHAR2(1000),
    ActionByUserUno       NUMBER,
    ActionOn              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDAEAudit_Rule FOREIGN KEY (AutoEscalationRuleUno) REFERENCES TblMstSDAutoEscalationRule(AutoEscalationRuleUno),
    CONSTRAINT FK_TrnSDAEAudit_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDAEAudit_ByUser FOREIGN KEY (ActionByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDAEAudit_Action CHECK (ActionCode IN ('SUGGESTED','ESCALATED','SKIPPED','FAILED')),
    CONSTRAINT CK_TrnSDAEAudit_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDAEAudit_TicketRule ON TblTrnSDAutoEscalationAudit(TicketUno, AutoEscalationRuleUno, ActionOn);

CREATE TABLE TblTrnSDPatternCluster (
    PatternClusterUno     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatternKey            VARCHAR2(300) NOT NULL,
    PatternTypeCode       VARCHAR2(40) NOT NULL, -- INCIDENT_REPEAT/SR_REPEAT/CROSS_REPEAT
    AffectedServiceUno    NUMBER,
    CategoryUno           NUMBER,
    SubTypeUno            NUMBER,
    WindowStartOn         TIMESTAMP(6) NOT NULL,
    WindowEndOn           TIMESTAMP(6) NOT NULL,
    TicketCount           NUMBER NOT NULL,
    HighPriorityCount     NUMBER DEFAULT 0 NOT NULL,
    SeverityScore         NUMBER(7,2),
    IsPotentialIssue      NUMBER(1) DEFAULT 1 NOT NULL,
    LastEvaluatedOn       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDPattern_Service FOREIGN KEY (AffectedServiceUno) REFERENCES TblMstSDAffectedService(AffectedServiceUno),
    CONSTRAINT FK_TrnSDPattern_Category FOREIGN KEY (CategoryUno) REFERENCES TblMstSDCategory(CategoryUno),
    CONSTRAINT FK_TrnSDPattern_SubType FOREIGN KEY (SubTypeUno) REFERENCES TblMstSDSubType(SubTypeUno),
    CONSTRAINT CK_TrnSDPattern_Type CHECK (PatternTypeCode IN ('INCIDENT_REPEAT','SR_REPEAT','CROSS_REPEAT')),
    CONSTRAINT CK_TrnSDPattern_Potential CHECK (IsPotentialIssue IN (0,1)),
    CONSTRAINT CK_TrnSDPattern_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDPatternTicket (
    PatternTicketUno      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatternClusterUno     NUMBER NOT NULL,
    TicketUno             NUMBER NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDPatternTicket_Cluster FOREIGN KEY (PatternClusterUno) REFERENCES TblTrnSDPatternCluster(PatternClusterUno),
    CONSTRAINT FK_TrnSDPatternTicket_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT UQ_TrnSDPatternTicket UNIQUE (PatternClusterUno, TicketUno),
    CONSTRAINT CK_TrnSDPatternTicket_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDProblemSuggestion (
    ProblemSuggestionUno  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatternClusterUno     NUMBER NOT NULL,
    SuggestedTitleEn      VARCHAR2(500) NOT NULL,
    SuggestedTitleAr      NVARCHAR2(500),
    SuggestedReasonEn     VARCHAR2(2000),
    SuggestedReasonAr     NVARCHAR2(2000),
    SuggestedPriorityUno  NUMBER,
    ConfidencePercent     NUMBER(5,2),
    SuggestionStatusCode  VARCHAR2(30) DEFAULT 'OPEN' NOT NULL, -- OPEN/ACCEPTED/REJECTED/CONVERTED
    SuggestedOn           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ReviewedByUserUno     NUMBER,
    ReviewedOn            TIMESTAMP(6),
    ConvertedProblemTicketUno NUMBER,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDPrbSug_Cluster FOREIGN KEY (PatternClusterUno) REFERENCES TblTrnSDPatternCluster(PatternClusterUno),
    CONSTRAINT FK_TrnSDPrbSug_Priority FOREIGN KEY (SuggestedPriorityUno) REFERENCES TblMstSDPriority(PriorityUno),
    CONSTRAINT FK_TrnSDPrbSug_ReviewedBy FOREIGN KEY (ReviewedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT FK_TrnSDPrbSug_ProblemTicket FOREIGN KEY (ConvertedProblemTicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT CK_TrnSDPrbSug_Status CHECK (SuggestionStatusCode IN ('OPEN','ACCEPTED','REJECTED','CONVERTED')),
    CONSTRAINT CK_TrnSDPrbSug_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDFeedback (
    FeedbackUno           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FeedbackTypeCode      VARCHAR2(20) NOT NULL, -- FEEDBACK / SUGGESTION
    FeedbackCategoryUno   NUMBER,
    TicketUno             NUMBER,
    SourceSystemUno       NUMBER,
    SubmittedByUserUno    NUMBER,
    SubjectEn             VARCHAR2(300),
    SubjectAr             NVARCHAR2(300),
    FeedbackText          CLOB NOT NULL,
    ImpactAreaCode        VARCHAR2(30), -- PROCESS / SYSTEM / PEOPLE / POLICY / UX
    PriorityCode          VARCHAR2(20), -- LOW / MEDIUM / HIGH
    StatusCode            VARCHAR2(30) DEFAULT 'SUBMITTED' NOT NULL, -- SUBMITTED/UNDER_REVIEW/ACTIONED/CLOSED
    IsImprovementAccepted NUMBER(1) DEFAULT 0 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_TrnSDFeedback_Category FOREIGN KEY (FeedbackCategoryUno) REFERENCES TblMstSDFeedbackCategory(FeedbackCategoryUno),
    CONSTRAINT FK_TrnSDFeedback_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDFeedback_SourceSystem FOREIGN KEY (SourceSystemUno) REFERENCES TblMstSDSourceSystem(SourceSystemUno),
    CONSTRAINT FK_TrnSDFeedback_SubmittedBy FOREIGN KEY (SubmittedByUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDFeedback_Type CHECK (FeedbackTypeCode IN ('FEEDBACK','SUGGESTION')),
    CONSTRAINT CK_TrnSDFeedback_Accepted CHECK (IsImprovementAccepted IN (0,1)),
    CONSTRAINT CK_TrnSDFeedback_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDFeedback_Status ON TblTrnSDFeedback(StatusCode, EnteredOn);

CREATE TABLE TblTrnSDTicketQualityReview (
    QualityReviewUno      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketUno             NUMBER NOT NULL,
    ReviewerUserUno       NUMBER NOT NULL, -- audit team or quality reviewer
    ReviewTypeCode        VARCHAR2(30) NOT NULL, -- RANDOM/AUDIT/SLA_BREACH/COMPLAINT
    ReviewStatusCode      VARCHAR2(30) DEFAULT 'OPEN' NOT NULL, -- OPEN/COMPLETED/REOPENED
    OverallScorePercent   NUMBER(5,2),
    ReviewSummaryEn       VARCHAR2(2000),
    ReviewSummaryAr       NVARCHAR2(2000),
    ReviewedOn            TIMESTAMP(6),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDQualityReview_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT FK_TrnSDQualityReview_Reviewer FOREIGN KEY (ReviewerUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDQualityReview_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDTicketQualityReviewItem (
    QualityReviewItemUno  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    QualityReviewUno      NUMBER NOT NULL,
    QualityParameterUno   NUMBER NOT NULL,
    ScorePercent          NUMBER(5,2),
    ObservationEn         VARCHAR2(2000),
    ObservationAr         NVARCHAR2(2000),
    IsPass                NUMBER(1) DEFAULT 0 NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDQualityItem_Review FOREIGN KEY (QualityReviewUno) REFERENCES TblTrnSDTicketQualityReview(QualityReviewUno),
    CONSTRAINT FK_TrnSDQualityItem_Parameter FOREIGN KEY (QualityParameterUno) REFERENCES TblMstSDQualityParameter(QualityParameterUno),
    CONSTRAINT UQ_TrnSDQualityItem UNIQUE (QualityReviewUno, QualityParameterUno),
    CONSTRAINT CK_TrnSDQualityItem_Pass CHECK (IsPass IN (0,1)),
    CONSTRAINT CK_TrnSDQualityItem_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDManagerCaseReview (
    ManagerCaseReviewUno  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReviewRoleCode        VARCHAR2(40) NOT NULL, -- SERVICE_DESK_MANAGER/CHANGE_MANAGER/PROBLEM_MANAGER
    ReviewerUserUno       NUMBER NOT NULL,
    ReviewPeriodTypeCode  VARCHAR2(20) NOT NULL, -- DAILY/WEEKLY/MONTHLY/QUARTERLY/ADHOC
    ReviewStartOn         TIMESTAMP(6),
    ReviewEndOn           TIMESTAMP(6),
    ReviewSummaryEn       VARCHAR2(2000),
    ReviewSummaryAr       NVARCHAR2(2000),
    RiskLevelCode         VARCHAR2(20), -- LOW/MEDIUM/HIGH/CRITICAL
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDMgrReview_Reviewer FOREIGN KEY (ReviewerUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT CK_TrnSDMgrReview_Role CHECK (ReviewRoleCode IN ('SERVICE_DESK_MANAGER','CHANGE_MANAGER','PROBLEM_MANAGER')),
    CONSTRAINT CK_TrnSDMgrReview_Period CHECK (ReviewPeriodTypeCode IN ('DAILY','WEEKLY','MONTHLY','QUARTERLY','ADHOC')),
    CONSTRAINT CK_TrnSDMgrReview_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDManagerCaseReviewTicket (
    ManagerReviewTicketUno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ManagerCaseReviewUno  NUMBER NOT NULL,
    TicketUno             NUMBER NOT NULL,
    ReviewOutcomeCode     VARCHAR2(30), -- OK/NEEDS_ACTION/ESCALATE/REOPEN
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDMgrReviewT_Review FOREIGN KEY (ManagerCaseReviewUno) REFERENCES TblTrnSDManagerCaseReview(ManagerCaseReviewUno),
    CONSTRAINT FK_TrnSDMgrReviewT_Ticket FOREIGN KEY (TicketUno) REFERENCES TblTrnSDTicket(TicketUno),
    CONSTRAINT UQ_TrnSDMgrReviewT UNIQUE (ManagerCaseReviewUno, TicketUno),
    CONSTRAINT CK_TrnSDMgrReviewT_IsActive CHECK (IsActive IN (0,1))
);

CREATE TABLE TblTrnSDCorrectiveAction (
    CorrectiveActionUno   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SourceEntityTypeCode  VARCHAR2(40) NOT NULL, -- TICKET/QUALITY_REVIEW/MANAGER_REVIEW/PROBLEM/CHANGE/FEEDBACK/SUMMARY
    SourceEntityUno       NUMBER NOT NULL,
    ActionTitleEn         VARCHAR2(300) NOT NULL,
    ActionTitleAr         NVARCHAR2(300),
    ActionDetailEn        VARCHAR2(2000),
    ActionDetailAr        NVARCHAR2(2000),
    OwnerUserUno          NUMBER,
    OwnerSupportLevelUno  NUMBER,
    TargetOn              TIMESTAMP(6),
    ActionStatusCode      VARCHAR2(30) DEFAULT 'OPEN' NOT NULL, -- OPEN/IN_PROGRESS/COMPLETED/CANCELLED/OVERDUE
    CompletionRemarkEn    VARCHAR2(2000),
    CompletionRemarkAr    NVARCHAR2(2000),
    CompletedOn           TIMESTAMP(6),
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDCorrAct_OwnerUser FOREIGN KEY (OwnerUserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT FK_TrnSDCorrAct_OwnerLevel FOREIGN KEY (OwnerSupportLevelUno) REFERENCES TblMstSDSupportLevel(SupportLevelUno),
    CONSTRAINT CK_TrnSDCorrAct_IsActive CHECK (IsActive IN (0,1))
);

CREATE INDEX IX_TrnSDCorrAct_Status ON TblTrnSDCorrectiveAction(ActionStatusCode, TargetOn);

-- KPI snapshots for periodic management summaries (weekly/monthly/quarterly)
CREATE TABLE TblTrnSDKPISnapshot (
    KPISnapshotUno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PeriodTypeCode        VARCHAR2(20) NOT NULL, -- WEEKLY/MONTHLY/QUARTERLY
    PeriodStartDate       DATE NOT NULL,
    PeriodEndDate         DATE NOT NULL,
    ScopeTypeCode         VARCHAR2(20) NOT NULL, -- OVERALL/DEPARTMENT/SECTION/AGENT
    DepartmentUno         NUMBER,
    SectionUno            NUMBER,
    UserUno               NUMBER,
    MetricCode            VARCHAR2(60) NOT NULL, -- OPEN_COUNT/DELAYED_COUNT/SLA_PCT/AVG_RES_HOURS...
    MetricValue           NUMBER(18,4) NOT NULL,
    SnapshotOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive              NUMBER(1) DEFAULT 1 NOT NULL,
    EnteredOn             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EnteredBy             VARCHAR2(128),
    ModifiedOn            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy            VARCHAR2(128),
    DeletedOn             TIMESTAMP(6),
    DeletedBy             VARCHAR2(128),
    CONSTRAINT FK_TrnSDKPI_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstSDDepartment(DepartmentUno),
    CONSTRAINT FK_TrnSDKPI_Section FOREIGN KEY (SectionUno) REFERENCES TblMstSDSection(SectionUno),
    CONSTRAINT FK_TrnSDKPI_User FOREIGN KEY (UserUno) REFERENCES TblMstSDUser(UserUno),
    CONSTRAINT UQ_TrnSDKPI_Unique UNIQUE (PeriodTypeCode, PeriodStartDate, PeriodEndDate, ScopeTypeCode, DepartmentUno, SectionUno, UserUno, MetricCode),
    CONSTRAINT CK_TrnSDKPI_Period CHECK (PeriodTypeCode IN ('WEEKLY','MONTHLY','QUARTERLY')),
    CONSTRAINT CK_TrnSDKPI_Scope CHECK (ScopeTypeCode IN ('OVERALL','DEPARTMENT','SECTION','AGENT')),
    CONSTRAINT CK_TrnSDKPI_IsActive CHECK (IsActive IN (0,1))
);

-- ------------------------------------------------------------
-- Reporting views for dashboards and management monitoring
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW VRptSDAgentKPILive AS
SELECT
    u.UserUno AS AgentUserUno,
    u.DisplayNameEn AS AgentNameEn,
    u.TeamUno,
    u.DepartmentUno,
    u.SectionUno,
    SUM(CASE WHEN t.TicketUno IS NOT NULL AND NVL(ts.IsTerminal,0)=0 THEN 1 ELSE 0 END) AS OpenTicketCount,
    SUM(
        CASE
            WHEN t.TicketUno IS NOT NULL
                 AND NVL(ts.IsTerminal,0)=0
                 AND SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
            THEN 1 ELSE 0
        END
    ) AS DelayedTicketCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.TicketUno IS NOT NULL
                     AND NVL(ts.IsTerminal,0)=0
                     AND SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(SUM(CASE WHEN t.TicketUno IS NOT NULL AND NVL(ts.IsTerminal,0)=0 THEN 1 ELSE 0 END),0),
        2
    ) AS DelayedPercent,
    ROUND(
        AVG(
            CASE
                WHEN t.ResolvedOn IS NOT NULL
                     AND t.ResolvedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(7,'DAY')
                THEN (CAST(t.ResolvedOn AS DATE) - CAST(t.CreatedOn AS DATE)) * 24
            END
        ),
        2
    ) AS AvgResolutionHours7D,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.CreatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY')
                     AND t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(SUM(CASE WHEN t.CreatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY') THEN 1 ELSE 0 END),0),
        2
    ) AS SLACompliancePct30D,
    SUM(CASE WHEN e.EscalationUno IS NOT NULL AND e.EscalatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY') THEN 1 ELSE 0 END) AS EscalationInCount30D
FROM TblMstSDUser u
LEFT JOIN TblTrnSDTicket t
       ON t.AssignedToUserUno = u.UserUno
      AND t.IsActive = 1
LEFT JOIN TblMstSDTicketStatus ts
       ON ts.TicketStatusUno = t.TicketStatusUno
LEFT JOIN TblMstSDPriority p
       ON p.PriorityUno = t.PriorityUno
LEFT JOIN TblTrnSDEscalation e
       ON e.TicketUno = t.TicketUno
      AND e.ToSupportLevelUno = u.SupportLevelUno
      AND e.IsActive = 1
WHERE u.IsAgent = 1
  AND u.IsActive = 1
GROUP BY u.UserUno, u.DisplayNameEn, u.TeamUno, u.DepartmentUno, u.SectionUno;

CREATE OR REPLACE VIEW VRptSDOverallKPILive AS
SELECT
    COUNT(*) AS TotalTicketCount,
    SUM(CASE WHEN NVL(ts.IsTerminal,0)=0 THEN 1 ELSE 0 END) AS OpenTicketCount,
    SUM(
        CASE
            WHEN NVL(ts.IsTerminal,0)=0
                 AND SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
            THEN 1 ELSE 0
        END
    ) AS DelayedTicketCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.CreatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY')
                     AND t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(SUM(CASE WHEN t.CreatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY') THEN 1 ELSE 0 END),0),
        2
    ) AS OverallSLACompliancePct30D,
    ROUND(
        AVG(CASE WHEN t.ResolvedOn IS NOT NULL THEN (CAST(t.ResolvedOn AS DATE) - CAST(t.CreatedOn AS DATE)) * 24 END),
        2
    ) AS AvgResolutionHours,
    SUM(CASE WHEN e.EscalationUno IS NOT NULL AND e.EscalatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY') THEN 1 ELSE 0 END) AS EscalationCount30D,
    SUM(CASE WHEN fb.FeedbackTypeCode='SUGGESTION' AND fb.IsImprovementAccepted=1 THEN 1 ELSE 0 END) AS AcceptedSuggestionCount
FROM TblTrnSDTicket t
LEFT JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
LEFT JOIN TblTrnSDEscalation e ON e.TicketUno = t.TicketUno AND e.IsActive = 1
LEFT JOIN TblTrnSDFeedback fb ON fb.TicketUno = t.TicketUno AND fb.IsActive = 1
WHERE t.IsActive = 1;

CREATE OR REPLACE VIEW VRptSDDepartmentSLALive AS
SELECT
    d.DepartmentUno,
    d.DepartmentCode,
    d.DepartmentNameEn,
    COUNT(t.TicketUno) AS TotalTicketCount,
    SUM(CASE WHEN NVL(ts.IsTerminal,0)=0 THEN 1 ELSE 0 END) AS OpenTicketCount,
    SUM(
        CASE
            WHEN NVL(ts.IsTerminal,0)=0
                 AND SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
            THEN 1 ELSE 0
        END
    ) AS DelayedTicketCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(COUNT(t.TicketUno),0),
        2
    ) AS SLACompliancePct
FROM TblMstSDDepartment d
LEFT JOIN (
    SELECT
        t1.*,
        NVL(t1.RequesterDepartmentUno, su.DepartmentUno) AS EffectiveDepartmentUno
    FROM TblTrnSDTicket t1
    LEFT JOIN TblMstSDUser su
           ON su.UserUno = t1.SubmittedByUserUno
    WHERE t1.IsActive = 1
) t
       ON t.EffectiveDepartmentUno = d.DepartmentUno
LEFT JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
WHERE d.IsActive = 1
GROUP BY d.DepartmentUno, d.DepartmentCode, d.DepartmentNameEn;

CREATE OR REPLACE VIEW VRptSDSectionSLALive AS
SELECT
    s.SectionUno,
    s.SectionCode,
    s.SectionNameEn,
    s.DepartmentUno,
    COUNT(t.TicketUno) AS TotalTicketCount,
    SUM(CASE WHEN NVL(ts.IsTerminal,0)=0 THEN 1 ELSE 0 END) AS OpenTicketCount,
    SUM(
        CASE
            WHEN NVL(ts.IsTerminal,0)=0
                 AND SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
            THEN 1 ELSE 0
        END
    ) AS DelayedTicketCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(COUNT(t.TicketUno),0),
        2
    ) AS SLACompliancePct
FROM TblMstSDSection s
LEFT JOIN (
    SELECT
        t1.*,
        NVL(t1.RequesterSectionUno, su.SectionUno) AS EffectiveSectionUno
    FROM TblTrnSDTicket t1
    LEFT JOIN TblMstSDUser su
           ON su.UserUno = t1.SubmittedByUserUno
    WHERE t1.IsActive = 1
) t
       ON t.EffectiveSectionUno = s.SectionUno
LEFT JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
WHERE s.IsActive = 1
GROUP BY s.SectionUno, s.SectionCode, s.SectionNameEn, s.DepartmentUno;

-- Candidate patterns to suggest problem records automatically
CREATE OR REPLACE VIEW VRptSDProblemSuggestionCandidate AS
SELECT
    t.AffectedServiceUno,
    svc.ServiceNameEn AS AffectedServiceNameEn,
    t.CategoryUno,
    c.CategoryNameEn,
    t.SubTypeUno,
    st.SubTypeNameEn,
    COUNT(*) AS RepeatedTicketCount30D,
    SUM(CASE WHEN p.PriorityCode IN ('P1','P2') THEN 1 ELSE 0 END) AS HighPriorityCount30D,
    ROUND(LEAST(99, (COUNT(*) * 12) + (SUM(CASE WHEN p.PriorityCode IN ('P1','P2') THEN 1 ELSE 0 END) * 6)), 2) AS ConfidencePercent,
    'Recurring issues in ' || NVL(svc.ServiceNameEn, 'Unspecified Service') || ' / ' || NVL(st.SubTypeNameEn, 'General') AS SuggestedProblemTitleEn
FROM TblTrnSDTicket t
JOIN TblMstSDTicketType tt ON tt.TicketTypeUno = t.TicketTypeUno
LEFT JOIN TblMstSDAffectedService svc ON svc.AffectedServiceUno = t.AffectedServiceUno
LEFT JOIN TblMstSDCategory c ON c.CategoryUno = t.CategoryUno
LEFT JOIN TblMstSDSubType st ON st.SubTypeUno = t.SubTypeUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
WHERE t.IsActive = 1
  AND tt.TicketTypeCode IN ('INCIDENT','SERVICE_REQUEST')
  AND t.CreatedOn >= SYSTIMESTAMP - NUMTODSINTERVAL(30,'DAY')
GROUP BY t.AffectedServiceUno, svc.ServiceNameEn, t.CategoryUno, c.CategoryNameEn, t.SubTypeUno, st.SubTypeNameEn
HAVING COUNT(*) >= 3;

-- Tickets that crossed configured auto-escalation thresholds
CREATE OR REPLACE VIEW VRptSDAutoEscalationDue AS
SELECT
    t.TicketUno,
    t.TicketNo,
    t.CurrentSupportLevelUno,
    r.AutoEscalationRuleUno,
    r.RuleCode,
    r.ToSupportLevelUno,
    ROUND((CAST(SYSTIMESTAMP AS DATE) - CAST(t.CreatedOn AS DATE)) * 24 * 60, 2) AS ElapsedMinutes,
    ROUND(NVL(p.ResponseSlaHours,24) * 60, 2) AS SlaMinutes,
    ROUND(((CAST(SYSTIMESTAMP AS DATE) - CAST(t.CreatedOn AS DATE)) * 24 * 60) / NULLIF((NVL(p.ResponseSlaHours,24) * 60),0) * 100, 2) AS ConsumedSlaPercent
FROM TblTrnSDTicket t
JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
JOIN TblMstSDAutoEscalationRule r
  ON r.IsActive = 1
 AND (r.TicketTypeUno IS NULL OR r.TicketTypeUno = t.TicketTypeUno)
 AND (r.PriorityUno IS NULL OR r.PriorityUno = t.PriorityUno)
 AND (r.FromSupportLevelUno IS NULL OR r.FromSupportLevelUno = t.CurrentSupportLevelUno)
WHERE t.IsActive = 1
  AND NVL(ts.IsTerminal,0) = 0
  AND (
      (r.TriggerAfterMinutes IS NOT NULL AND ((CAST(SYSTIMESTAMP AS DATE) - CAST(t.CreatedOn AS DATE)) * 24 * 60) >= r.TriggerAfterMinutes)
      OR
      (r.TriggerPercentSla IS NOT NULL AND (((CAST(SYSTIMESTAMP AS DATE) - CAST(t.CreatedOn AS DATE)) * 24 * 60) / NULLIF((NVL(p.ResponseSlaHours,24) * 60),0) * 100) >= r.TriggerPercentSla)
  )
  AND NOT EXISTS (
      SELECT 1
      FROM TblTrnSDAutoEscalationAudit a
      WHERE a.TicketUno = t.TicketUno
        AND a.AutoEscalationRuleUno = r.AutoEscalationRuleUno
        AND a.ActionCode = 'ESCALATED'
        AND a.IsActive = 1
  );

-- Weekly/Monthly/Quarterly management summary for service request impact
CREATE OR REPLACE VIEW VRptSDServiceRequestSummaryPeriod AS
SELECT
    'WEEKLY' AS PeriodTypeCode,
    TRUNC(CAST(t.CreatedOn AS DATE), 'IW') AS PeriodStartDate,
    TRUNC(CAST(t.CreatedOn AS DATE), 'IW') + 6 AS PeriodEndDate,
    COUNT(*) AS ServiceRequestCount,
    SUM(CASE WHEN i.ImpactCode = 'HIGH' THEN 1 ELSE 0 END) AS HighImpactCount,
    SUM(
        CASE
            WHEN SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                 AND NVL(ts.IsTerminal,0)=0
            THEN 1 ELSE 0
        END
    ) AS DelayedCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(COUNT(*),0),
        2
    ) AS SLACompliancePct
FROM TblTrnSDTicket t
JOIN TblMstSDTicketType tt ON tt.TicketTypeUno = t.TicketTypeUno AND tt.TicketTypeCode = 'SERVICE_REQUEST'
LEFT JOIN TblMstSDImpact i ON i.ImpactUno = t.ImpactUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
LEFT JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
WHERE t.IsActive = 1
GROUP BY TRUNC(CAST(t.CreatedOn AS DATE), 'IW')
UNION ALL
SELECT
    'MONTHLY' AS PeriodTypeCode,
    TRUNC(CAST(t.CreatedOn AS DATE), 'MM') AS PeriodStartDate,
    LAST_DAY(CAST(t.CreatedOn AS DATE)) AS PeriodEndDate,
    COUNT(*) AS ServiceRequestCount,
    SUM(CASE WHEN i.ImpactCode = 'HIGH' THEN 1 ELSE 0 END) AS HighImpactCount,
    SUM(
        CASE
            WHEN SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                 AND NVL(ts.IsTerminal,0)=0
            THEN 1 ELSE 0
        END
    ) AS DelayedCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(COUNT(*),0),
        2
    ) AS SLACompliancePct
FROM TblTrnSDTicket t
JOIN TblMstSDTicketType tt ON tt.TicketTypeUno = t.TicketTypeUno AND tt.TicketTypeCode = 'SERVICE_REQUEST'
LEFT JOIN TblMstSDImpact i ON i.ImpactUno = t.ImpactUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
LEFT JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
WHERE t.IsActive = 1
GROUP BY TRUNC(CAST(t.CreatedOn AS DATE), 'MM'), LAST_DAY(CAST(t.CreatedOn AS DATE))
UNION ALL
SELECT
    'QUARTERLY' AS PeriodTypeCode,
    TRUNC(CAST(t.CreatedOn AS DATE), 'Q') AS PeriodStartDate,
    ADD_MONTHS(TRUNC(CAST(t.CreatedOn AS DATE), 'Q'), 3) - 1 AS PeriodEndDate,
    COUNT(*) AS ServiceRequestCount,
    SUM(CASE WHEN i.ImpactCode = 'HIGH' THEN 1 ELSE 0 END) AS HighImpactCount,
    SUM(
        CASE
            WHEN SYSTIMESTAMP > NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                 AND NVL(ts.IsTerminal,0)=0
            THEN 1 ELSE 0
        END
    ) AS DelayedCount,
    ROUND(
        100 * SUM(
            CASE
                WHEN t.FirstResponseOn IS NOT NULL
                     AND t.FirstResponseOn <= NVL(t.ResponseSlaDueOn, t.CreatedOn + NUMTODSINTERVAL(NVL(p.ResponseSlaHours,24),'HOUR'))
                THEN 1 ELSE 0
            END
        ) / NULLIF(COUNT(*),0),
        2
    ) AS SLACompliancePct
FROM TblTrnSDTicket t
JOIN TblMstSDTicketType tt ON tt.TicketTypeUno = t.TicketTypeUno AND tt.TicketTypeCode = 'SERVICE_REQUEST'
LEFT JOIN TblMstSDImpact i ON i.ImpactUno = t.ImpactUno
LEFT JOIN TblMstSDPriority p ON p.PriorityUno = t.PriorityUno
LEFT JOIN TblMstSDTicketStatus ts ON ts.TicketStatusUno = t.TicketStatusUno
WHERE t.IsActive = 1
GROUP BY TRUNC(CAST(t.CreatedOn AS DATE), 'Q'), ADD_MONTHS(TRUNC(CAST(t.CreatedOn AS DATE), 'Q'), 3) - 1;

-- ============================================================
-- 3) Minimal seed data for menu-driven support levels/types
-- ============================================================

INSERT INTO TblMstSDSupportLevel (SupportLevelCode, SupportLevelNameEn, SupportLevelNameAr, LevelSortOrder) VALUES ('SUPPORT_TEAM', 'Support Team', N'فريق الدعم', 0);
INSERT INTO TblMstSDSupportLevel (SupportLevelCode, SupportLevelNameEn, SupportLevelNameAr, LevelSortOrder) VALUES ('L1', 'L1 Agent', N'وكيل المستوى الأول', 1);
INSERT INTO TblMstSDSupportLevel (SupportLevelCode, SupportLevelNameEn, SupportLevelNameAr, LevelSortOrder) VALUES ('L2', 'L2 Agent', N'وكيل المستوى الثاني', 2);
INSERT INTO TblMstSDSupportLevel (SupportLevelCode, SupportLevelNameEn, SupportLevelNameAr, LevelSortOrder) VALUES ('L3', 'L3 / SME', N'خبير المستوى الثالث', 3);
INSERT INTO TblMstSDSupportLevel (SupportLevelCode, SupportLevelNameEn, SupportLevelNameAr, LevelSortOrder) VALUES ('MANAGER', 'Service Desk Manager', N'مدير مركز الخدمة', 4);

INSERT INTO TblMstSDTicketType (TicketTypeCode, TicketTypeNameEn, TicketTypeNameAr) VALUES ('INCIDENT', 'Incident', N'حادث');
INSERT INTO TblMstSDTicketType (TicketTypeCode, TicketTypeNameEn, TicketTypeNameAr) VALUES ('SERVICE_REQUEST', 'Service Request', N'طلب خدمة');
INSERT INTO TblMstSDTicketType (TicketTypeCode, TicketTypeNameEn, TicketTypeNameAr) VALUES ('PROBLEM', 'Problem', N'مشكلة');
INSERT INTO TblMstSDTicketType (TicketTypeCode, TicketTypeNameEn, TicketTypeNameAr) VALUES ('CHANGE_REQUEST', 'Change Request', N'طلب تغيير');

INSERT INTO TblMstSDPriority (PriorityCode, PriorityNameEn, PriorityNameAr, ResponseSlaHours, SortOrder) VALUES ('P1', 'Critical', N'حرج', 1, 1);
INSERT INTO TblMstSDPriority (PriorityCode, PriorityNameEn, PriorityNameAr, ResponseSlaHours, SortOrder) VALUES ('P2', 'High', N'عالٍ', 4, 2);
INSERT INTO TblMstSDPriority (PriorityCode, PriorityNameEn, PriorityNameAr, ResponseSlaHours, SortOrder) VALUES ('P3', 'Medium', N'متوسط', 8, 3);
INSERT INTO TblMstSDPriority (PriorityCode, PriorityNameEn, PriorityNameAr, ResponseSlaHours, SortOrder) VALUES ('P4', 'Low', N'منخفض', 24, 4);

COMMIT;
