-- RBAC Admin Portal schema for PostgreSQL
-- Naming convention requested:
--   * Master tables      : TblMstRBAC...
--   * Transaction tables : TblTrnRBAC...
--   * Primary key names  : ...Uno
--   * All primary keys are identity columns.
-- Bilingual support:
--   * English columns use suffix En (VARCHAR)
--   * Arabic columns use suffix Ar (VARCHAR, UTF-8)
-- Audit fields:
--   * EnteredOn, EnteredBy, ModifiedOn, ModifiedBy, DeletedOn, DeletedBy
-- Active flag:
--   * IsActive SMALLINT in all tables (1=active, 0=inactive)

-- ============================================================
-- 1) MASTER TABLES (TblMstRBAC*)
-- ============================================================

CREATE TABLE TblMstRBACCompany (
    CompanyUno          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyCode         VARCHAR(30) NOT NULL,
    CompanyNameEn       VARCHAR(120) NOT NULL,
    CompanyNameAr       VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT UQ_MstCompany_Code UNIQUE (CompanyCode),
    CONSTRAINT CK_MstCompany_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblMstRBACDepartment (
    DepartmentUno       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyUno          BIGINT NOT NULL,
    DepartmentCode      VARCHAR(30) NOT NULL,
    DepartmentNameEn    VARCHAR(120) NOT NULL,
    DepartmentNameAr    VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstDept_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT UQ_MstDept_CompCode UNIQUE (CompanyUno, DepartmentCode),
    CONSTRAINT CK_MstDept_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstDept_Company ON TblMstRBACDepartment(CompanyUno);

CREATE TABLE TblMstRBACDivision (
    DivisionUno         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DepartmentUno       BIGINT NOT NULL,
    DivisionCode        VARCHAR(30) NOT NULL,
    DivisionNameEn      VARCHAR(120) NOT NULL,
    DivisionNameAr      VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstDivision_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstRBACDepartment(DepartmentUno),
    CONSTRAINT UQ_MstDivision_UnoDept UNIQUE (DivisionUno, DepartmentUno),
    CONSTRAINT UQ_MstDivision_DeptCode UNIQUE (DepartmentUno, DivisionCode),
    CONSTRAINT CK_MstDivision_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstDivision_Department ON TblMstRBACDivision(DepartmentUno);

CREATE TABLE TblMstRBACSection (
    SectionUno          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DivisionUno         BIGINT NOT NULL,
    SectionCode         VARCHAR(30) NOT NULL,
    SectionNameEn       VARCHAR(120) NOT NULL,
    SectionNameAr       VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstSection_Division FOREIGN KEY (DivisionUno) REFERENCES TblMstRBACDivision(DivisionUno),
    CONSTRAINT UQ_MstSection_UnoDiv UNIQUE (SectionUno, DivisionUno),
    CONSTRAINT UQ_MstSection_DivCode UNIQUE (DivisionUno, SectionCode),
    CONSTRAINT CK_MstSection_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstSection_Division ON TblMstRBACSection(DivisionUno);

CREATE TABLE TblMstRBACCountry (
    CountryUno          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Iso2Code            CHAR(2) NOT NULL,
    CountryNameEn       VARCHAR(120) NOT NULL,
    CountryNameAr       VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT UQ_MstCountry_Iso2 UNIQUE (Iso2Code),
    CONSTRAINT UQ_MstCountry_NameEn UNIQUE (CountryNameEn),
    CONSTRAINT CK_MstCountry_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblMstRBACEmbassy (
    EmbassyUno          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CountryUno          BIGINT NOT NULL,
    EmbassyCode         VARCHAR(40) NOT NULL,
    EmbassyNameEn       VARCHAR(200) NOT NULL,
    EmbassyNameAr       VARCHAR(200),
    EmbassyTypeCode       VARCHAR(30) DEFAULT 'EMBASSY' NOT NULL,
    CityNameEn          VARCHAR(120),
    CityNameAr          VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstEmb_Country FOREIGN KEY (CountryUno) REFERENCES TblMstRBACCountry(CountryUno),
    CONSTRAINT UQ_MstEmb_Code UNIQUE (EmbassyCode),
    CONSTRAINT UQ_MstEmb_CountryEn UNIQUE (CountryUno, EmbassyNameEn),
    CONSTRAINT CK_MstEmb_Type CHECK (EmbassyTypeCode IN ('EMBASSY', 'CONSULATE', 'HIGH_COMMISSION', 'OTHER')),
    CONSTRAINT CK_MstEmb_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstEmb_Country ON TblMstRBACEmbassy(CountryUno);

CREATE TABLE TblMstRBACModule (
    ModuleUno           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleCode          VARCHAR(30) NOT NULL,
    ModuleNameEn        VARCHAR(120) NOT NULL,
    ModuleNameAr        VARCHAR(120),
    IconName            VARCHAR(20),
    DescriptionEn       VARCHAR(1000),
    DescriptionAr       VARCHAR(1000),
    SortOrder           INTEGER DEFAULT 0 NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT UQ_MstModule_Code UNIQUE (ModuleCode),
    CONSTRAINT UQ_MstModule_NameEn UNIQUE (ModuleNameEn),
    CONSTRAINT CK_MstModule_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblMstRBACPage (
    PageUno             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleUno           BIGINT NOT NULL,
    PageCode            VARCHAR(40) NOT NULL,
    PageNameEn          VARCHAR(150) NOT NULL,
    PageNameAr          VARCHAR(150),
    RoutePath           VARCHAR(300),
    DescriptionEn       VARCHAR(1000),
    DescriptionAr       VARCHAR(1000),
    SortOrder           INTEGER DEFAULT 0 NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstPage_Module FOREIGN KEY (ModuleUno) REFERENCES TblMstRBACModule(ModuleUno),
    CONSTRAINT UQ_MstPage_Code UNIQUE (PageCode),
    CONSTRAINT UQ_MstPage_ModNameEn UNIQUE (ModuleUno, PageNameEn),
    CONSTRAINT CK_MstPage_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstPage_Module ON TblMstRBACPage(ModuleUno);

CREATE TABLE TblMstRBACAction (
    ActionUno           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PageUno             BIGINT NOT NULL,
    ActionCode          VARCHAR(60) NOT NULL,
    ActionNameEn        VARCHAR(150) NOT NULL,
    ActionNameAr        VARCHAR(150),
    ActionTypeCode VARCHAR(20) NOT NULL,
    DescriptionEn       VARCHAR(1000),
    DescriptionAr       VARCHAR(1000),
    SortOrder           INTEGER DEFAULT 0 NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstAction_Page FOREIGN KEY (PageUno) REFERENCES TblMstRBACPage(PageUno),
    CONSTRAINT UQ_MstAction_Code UNIQUE (ActionCode),
    CONSTRAINT UQ_MstAction_PageType UNIQUE (PageUno, ActionTypeCode),
    CONSTRAINT CK_MstAction_Type CHECK (ActionTypeCode IN ('VIEW', 'ADD', 'EDIT', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'CUSTOM')),
    CONSTRAINT CK_MstAction_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstAction_Page ON TblMstRBACAction(PageUno);

CREATE TABLE TblMstRBACRole (
    RoleUno             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleCode            VARCHAR(40) NOT NULL,
    RoleNameEn          VARCHAR(150) NOT NULL,
    RoleNameAr          VARCHAR(150),
    DescriptionEn       VARCHAR(1000),
    DescriptionAr       VARCHAR(1000),
    AccessModelCode       VARCHAR(20) DEFAULT 'USER_LINKED' NOT NULL,
    ScopeLevelCode        VARCHAR(20) DEFAULT 'GLOBAL' NOT NULL,
    IsSystemRole        CHAR(1) DEFAULT 'N' NOT NULL,
    IsSuperAdminRole    CHAR(1) DEFAULT 'N' NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT CK_MstRole_AccessModel CHECK (AccessModelCode IN ('USER_LINKED', 'GEO_SCOPED', 'GROUP_LINKED')),
    CONSTRAINT CK_MstRole_ScopeLevel CHECK (ScopeLevelCode IN ('GLOBAL', 'COUNTRY', 'EMBASSY')),
    CONSTRAINT CK_MstRole_IsSystem CHECK (IsSystemRole IN ('Y', 'N')),
    CONSTRAINT CK_MstRole_IsSuper CHECK (IsSuperAdminRole IN ('Y', 'N')),
    CONSTRAINT CK_MstRole_IsActive CHECK (IsActive IN (0, 1)),
    CONSTRAINT CK_MstRole_DelActive CHECK (DeletedOn IS NULL OR IsActive = 0)
);

-- Allow reuse of code/name after soft-delete (DeletedOn is not null)
CREATE UNIQUE INDEX UX_MstRole_Code_Act
    ON TblMstRBACRole (CASE WHEN DeletedOn IS NULL THEN RoleCode END);

CREATE UNIQUE INDEX UX_MstRole_NameEn_Act
    ON TblMstRBACRole (CASE WHEN DeletedOn IS NULL THEN RoleNameEn END);

CREATE INDEX IX_MstRole_AccessModel ON TblMstRBACRole(AccessModelCode);

-- Allowed email domains for user master onboarding.
CREATE TABLE TblMstRBACAllowedEmailDomain (
    AllowedEmailDomainUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmailDomain         VARCHAR(255) NOT NULL,
    DescriptionEn       VARCHAR(500),
    DescriptionAr       VARCHAR(500),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT CK_MstAllowDom_Format CHECK (
        INSTR(EmailDomain, '@') = 0 AND INSTR(EmailDomain, '.') > 1
    ),
    CONSTRAINT CK_MstAllowDom_IsActive CHECK (IsActive IN (0, 1))
);

-- Active unique domain list (case-insensitive); allows reuse after soft delete.
CREATE UNIQUE INDEX UX_MstAllowDom_Act
    ON TblMstRBACAllowedEmailDomain (CASE WHEN DeletedOn IS NULL THEN LOWER(EmailDomain) END);

CREATE TABLE TblMstRBACUser (
    UserUno             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeId          VARCHAR(40) NOT NULL,
    FirstNameEn         VARCHAR(80) NOT NULL,
    FirstNameAr         VARCHAR(80),
    LastNameEn          VARCHAR(80) NOT NULL,
    LastNameAr          VARCHAR(80),
    EmailAddr           VARCHAR(255) NOT NULL,
    StaffTypeCode       VARCHAR(20) DEFAULT 'PERMANENT' NOT NULL,
    AccountExpiryOn     TIMESTAMP NOT NULL,
    PasswordHash        VARCHAR(500) NOT NULL,
    PasswordChangedOn   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DesignationEn       VARCHAR(120),
    DesignationAr       VARCHAR(120),
    CompanyUno          BIGINT,
    DepartmentUno       BIGINT NOT NULL,
    DivisionUno         BIGINT NOT NULL,
    SectionUno          BIGINT,
    FailedPasswordAttemptCount SMALLINT DEFAULT 0 NOT NULL,
    IsAccountLocked     SMALLINT DEFAULT 0 NOT NULL,
    AccountLockedOn     TIMESTAMP,
    FirstLoginOn        TIMESTAMP,
    LastLoginOn         TIMESTAMP,
    LastFailedLoginOn   TIMESTAMP,
    ExternalSubjectId   VARCHAR(200),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT UQ_MstUser_Emp UNIQUE (EmployeeId),
    CONSTRAINT UQ_MstUser_Email UNIQUE (EmailAddr),
    CONSTRAINT FK_MstUser_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT FK_MstUser_Department FOREIGN KEY (DepartmentUno) REFERENCES TblMstRBACDepartment(DepartmentUno),
    CONSTRAINT FK_MstUser_Division FOREIGN KEY (DivisionUno) REFERENCES TblMstRBACDivision(DivisionUno),
    CONSTRAINT FK_MstUser_Section FOREIGN KEY (SectionUno) REFERENCES TblMstRBACSection(SectionUno),
    CONSTRAINT FK_MstUser_DivDept FOREIGN KEY (DivisionUno, DepartmentUno)
        REFERENCES TblMstRBACDivision(DivisionUno, DepartmentUno),
    CONSTRAINT FK_MstUser_SecDiv FOREIGN KEY (SectionUno, DivisionUno)
        REFERENCES TblMstRBACSection(SectionUno, DivisionUno),
    CONSTRAINT CK_MstUser_IsActive CHECK (IsActive IN (0, 1)),
    CONSTRAINT CK_MstUser_FailedPwd CHECK (FailedPasswordAttemptCount BETWEEN 0 AND 99),
    CONSTRAINT CK_MstUser_IsLocked CHECK (IsAccountLocked IN (0, 1)),
    CONSTRAINT CK_MstUser_LockRule CHECK (
        (FailedPasswordAttemptCount < 3) OR
        (FailedPasswordAttemptCount >= 3 AND IsAccountLocked = 1)
    ),
    CONSTRAINT CK_MstUser_LockTs CHECK (
        (IsAccountLocked = 0) OR
        (IsAccountLocked = 1 AND AccountLockedOn IS NOT NULL)
    ),
    CONSTRAINT CK_MstUser_StaffType CHECK (StaffTypeCode IN ('PERMANENT', 'EXTERNAL')),
    CONSTRAINT CK_MstUser_ExpiryLimit CHECK (
        (StaffTypeCode = 'PERMANENT' AND
            AccountExpiryOn >= EnteredOn AND
            AccountExpiryOn <= (EnteredOn + INTERVAL '12 months')
        ) OR
        (StaffTypeCode = 'EXTERNAL' AND
            AccountExpiryOn >= EnteredOn AND
            AccountExpiryOn <= (EnteredOn + INTERVAL '6 months')
        )
    )
);

CREATE INDEX IX_MstUser_Company ON TblMstRBACUser(CompanyUno);
CREATE INDEX IX_MstUser_Department ON TblMstRBACUser(DepartmentUno);
CREATE INDEX IX_MstUser_Division ON TblMstRBACUser(DivisionUno);
CREATE INDEX IX_MstUser_Section ON TblMstRBACUser(SectionUno);
CREATE INDEX IX_MstUser_ExpiryOn ON TblMstRBACUser(AccountExpiryOn);


-- Auto-derive expiry when not provided:
-- PERMANENT => EnteredOn + 12 months
-- EXTERNAL  => EnteredOn + 6 months

CREATE TABLE TblMstRBACUserGroup (
    UserGroupUno        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyUno          BIGINT NOT NULL,
    GroupCode           VARCHAR(50),
    GroupNameEn         VARCHAR(150) NOT NULL,
    GroupNameAr         VARCHAR(150),
    GroupTypeCode         VARCHAR(30) NOT NULL,
    DescriptionEn       VARCHAR(1000),
    DescriptionAr       VARCHAR(1000),
    RoleTemplateUno     BIGINT,
    EstimatedMembers    INTEGER,
    MembershipSourceCode  VARCHAR(30) DEFAULT 'ORG_CHART' NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_MstUserGroup_Company FOREIGN KEY (CompanyUno) REFERENCES TblMstRBACCompany(CompanyUno),
    CONSTRAINT FK_MstUserGroup_RoleTpl FOREIGN KEY (RoleTemplateUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_MstUserGroup_CompEn UNIQUE (CompanyUno, GroupNameEn),
    CONSTRAINT UQ_MstUserGroup_Code UNIQUE (GroupCode),
    CONSTRAINT CK_MstUserGroup_Type CHECK (GroupTypeCode IN ('DEPARTMENT_TEAM', 'PUBLIC_GROUP', 'EXTERNAL_PARTNER')),
    CONSTRAINT CK_MstUserGroup_Source CHECK (MembershipSourceCode IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL', 'PUBLIC')),
    CONSTRAINT CK_MstUserGroup_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_MstUserGroup_Company ON TblMstRBACUserGroup(CompanyUno);

-- ============================================================
-- 2) TRANSACTION TABLES (TblTrnRBAC*)
-- ============================================================

-- Keep last 5 password hashes per user for compliance checks.
CREATE TABLE TblTrnRBACUserPasswordHistory (
    PasswordHistoryUno  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno             BIGINT NOT NULL,
    PasswordHash        VARCHAR(500) NOT NULL,
    PasswordChangedOn   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnPwdHist_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnPwdHist_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnPwdHist_UserOn
    ON TblTrnRBACUserPasswordHistory(UserUno, PasswordChangedOn DESC);

-- Full application usage telemetry (page/action usage statistics source).
CREATE TABLE TblTrnRBACUserActivity (
    ActivityUno          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno              BIGINT,
    SessionCode          VARCHAR(120),
    RequestCode          VARCHAR(120),
    ActivityOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ActivityTypeCode VARCHAR(20) NOT NULL,
    ModuleUno            BIGINT,
    PageUno              BIGINT,
    ActionUno            BIGINT,
    RoutePath            VARCHAR(500),
    HttpMethodCode       VARCHAR(10),
    ResponseStatusCode   VARCHAR(10),
    DurationMs           BIGINT,
    IsAuthorized         SMALLINT DEFAULT 1 NOT NULL,
    ClientIpAddress      VARCHAR(64),
    UserAgent            VARCHAR(1000),
    DeviceCode           VARCHAR(40),
    DetailJson           JSONB,
    IsActive             SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn           TIMESTAMP,
    InactivatedOn        TIMESTAMP,
    InactivatedBy        VARCHAR(128),
    ActivatedOn          TIMESTAMP,
    ActivatedBy          VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy            VARCHAR(128),
    ModifiedOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy           VARCHAR(128),
    DeletedOn            TIMESTAMP,
    DeletedBy            VARCHAR(128),
    CONSTRAINT FK_TrnUserAct_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserAct_Module FOREIGN KEY (ModuleUno) REFERENCES TblMstRBACModule(ModuleUno),
    CONSTRAINT FK_TrnUserAct_Page FOREIGN KEY (PageUno) REFERENCES TblMstRBACPage(PageUno),
    CONSTRAINT FK_TrnUserAct_Action FOREIGN KEY (ActionUno) REFERENCES TblMstRBACAction(ActionUno),
    CONSTRAINT CK_TrnUserAct_Type CHECK (
        ActivityTypeCode IN ('PAGE_VIEW', 'ACTION_EXECUTE', 'LOGIN', 'LOGOUT', 'API_CALL', 'UNAUTHORIZED')
    ),
    CONSTRAINT CK_TrnUserAct_IsAuth CHECK (IsAuthorized IN (0, 1)),
    CONSTRAINT CK_TrnUserAct_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserAct_UserOn ON TblTrnRBACUserActivity(UserUno, ActivityOn DESC);
CREATE INDEX IX_TrnUserAct_PageOn ON TblTrnRBACUserActivity(PageUno, ActivityOn DESC);
CREATE INDEX IX_TrnUserAct_ActionOn ON TblTrnRBACUserActivity(ActionUno, ActivityOn DESC);
CREATE INDEX IX_TrnUserAct_TypeOn ON TblTrnRBACUserActivity(ActivityTypeCode, ActivityOn DESC);

-- Unauthorized access attempts by user (page/action/API/login).
CREATE TABLE TblTrnRBACUnauthAccess (
    UnauthAccessUno      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno              BIGINT,
    ActivityUno          BIGINT,
    AttemptOn            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AccessPointCode VARCHAR(20) NOT NULL,
    ModuleUno            BIGINT,
    PageUno              BIGINT,
    ActionUno            BIGINT,
    RoutePath            VARCHAR(500),
    DenialReasonCode     VARCHAR(40),
    ClientIpAddress      VARCHAR(64),
    UserAgent            VARCHAR(1000),
    DetailJson           JSONB,
    IsActive             SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn           TIMESTAMP,
    InactivatedOn        TIMESTAMP,
    InactivatedBy        VARCHAR(128),
    ActivatedOn          TIMESTAMP,
    ActivatedBy          VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy            VARCHAR(128),
    ModifiedOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy           VARCHAR(128),
    DeletedOn            TIMESTAMP,
    DeletedBy            VARCHAR(128),
    CONSTRAINT FK_TrnUnauth_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUnauth_Act FOREIGN KEY (ActivityUno) REFERENCES TblTrnRBACUserActivity(ActivityUno),
    CONSTRAINT FK_TrnUnauth_Module FOREIGN KEY (ModuleUno) REFERENCES TblMstRBACModule(ModuleUno),
    CONSTRAINT FK_TrnUnauth_Page FOREIGN KEY (PageUno) REFERENCES TblMstRBACPage(PageUno),
    CONSTRAINT FK_TrnUnauth_Action FOREIGN KEY (ActionUno) REFERENCES TblMstRBACAction(ActionUno),
    CONSTRAINT CK_TrnUnauth_AccessPt CHECK (AccessPointCode IN ('PAGE', 'ACTION', 'API', 'LOGIN')),
    CONSTRAINT CK_TrnUnauth_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUnauth_UserOn ON TblTrnRBACUnauthAccess(UserUno, AttemptOn DESC);
CREATE INDEX IX_TrnUnauth_Reason ON TblTrnRBACUnauthAccess(DenialReasonCode, AttemptOn DESC);

-- Security incidents (breach/suspicious behavior) for SOC/compliance review.
CREATE TABLE TblTrnRBACSecurityIncident (
    SecurityIncidentUno  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno              BIGINT,
    UnauthAccessUno      BIGINT,
    IncidentTypeCode     VARCHAR(30) NOT NULL,
    SeverityCode         VARCHAR(20) DEFAULT 'MEDIUM' NOT NULL,
    IncidentOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IncidentStatusCode   VARCHAR(20) DEFAULT 'OPEN' NOT NULL,
    DetectedByCode       VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL,
    ResolvedOn           TIMESTAMP,
    ResolvedByUserUno    BIGINT,
    ResolutionCommentEn  VARCHAR(1000),
    ResolutionCommentAr  VARCHAR(1000),
    DetailJson           JSONB,
    IsActive             SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn           TIMESTAMP,
    InactivatedOn        TIMESTAMP,
    InactivatedBy        VARCHAR(128),
    ActivatedOn          TIMESTAMP,
    ActivatedBy          VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy            VARCHAR(128),
    ModifiedOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy           VARCHAR(128),
    DeletedOn            TIMESTAMP,
    DeletedBy            VARCHAR(128),
    CONSTRAINT FK_TrnSecInc_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnSecInc_Unauth FOREIGN KEY (UnauthAccessUno) REFERENCES TblTrnRBACUnauthAccess(UnauthAccessUno),
    CONSTRAINT FK_TrnSecInc_ResolvedBy FOREIGN KEY (ResolvedByUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnSecInc_Type CHECK (
        IncidentTypeCode IN ('UNAUTHORIZED_ACCESS', 'BRUTE_FORCE', 'PRIV_ESCALATION', 'ANOMALOUS_USAGE', 'SUSPICIOUS_IP')
    ),
    CONSTRAINT CK_TrnSecInc_Severity CHECK (SeverityCode IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_TrnSecInc_Status CHECK (IncidentStatusCode IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'FALSE_POSITIVE')),
    CONSTRAINT CK_TrnSecInc_DetectBy CHECK (DetectedByCode IN ('SYSTEM', 'SOC', 'ADMIN')),
    CONSTRAINT CK_TrnSecInc_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnSecInc_UserOn ON TblTrnRBACSecurityIncident(UserUno, IncidentOn DESC);
CREATE INDEX IX_TrnSecInc_StSev ON TblTrnRBACSecurityIncident(IncidentStatusCode, SeverityCode);


-- Capture each login attempt in a separate audit table.
CREATE TABLE TblTrnRBACUserLoginAudit (
    UserLoginAuditUno   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno             BIGINT,
    AttemptLoginId      VARCHAR(255),
    AttemptOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LoginResultCode VARCHAR(20) NOT NULL,
    FailureReasonCode   VARCHAR(50),
    IpAddress           VARCHAR(64),
    UserAgent           VARCHAR(1000),
    SessionCode         VARCHAR(120),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnLoginAudit_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnLoginAudit_Result CHECK (LoginResultCode IN ('SUCCESS', 'FAILED', 'LOCKED', 'RESET_REQUIRED')),
    CONSTRAINT CK_TrnLoginAudit_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnLoginAudit_UserOn
    ON TblTrnRBACUserLoginAudit(UserUno, AttemptOn DESC);

-- Security event audit (password reset, lock/unlock, MFA changes, etc.).
CREATE TABLE TblTrnRBACUserSecurityAudit (
    UserSecurityAuditUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno             BIGINT NOT NULL,
    SecurityActionCode  VARCHAR(40) NOT NULL,
    ActionOn            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ActorUserUno        BIGINT,
    DetailJson          JSONB,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnSecAudit_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnSecAudit_Actor FOREIGN KEY (ActorUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnSecAudit_Action CHECK (
        SecurityActionCode IN ('PASSWORD_CHANGED', 'PASSWORD_RESET', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'LOGIN_POLICY_CHANGED')
    ),
    CONSTRAINT CK_TrnSecAudit_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnSecAudit_UserOn
    ON TblTrnRBACUserSecurityAudit(UserUno, ActionOn DESC);

-- User reactivation process: request + approval trail.
CREATE TABLE TblTrnRBACUserReactRequest (
    UserReactRequestUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RequestCode         VARCHAR(40) NOT NULL,
    UserUno             BIGINT NOT NULL,
    RequestedByUserUno  BIGINT NOT NULL,
    RequestReasonEn     VARCHAR(1000) NOT NULL,
    RequestReasonAr     VARCHAR(1000),
    RequestOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RequestStatusCode   VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    FinalDecisionOn     TIMESTAMP,
    FinalDecisionByUserUno BIGINT,
    FinalDecisionCommentEn VARCHAR(1000),
    FinalDecisionCommentAr VARCHAR(1000),
    ReactivatedOn       TIMESTAMP,
    ReactivatedByUserUno BIGINT,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT UQ_TrnUserReactReq_Code UNIQUE (RequestCode),
    CONSTRAINT FK_TrnUserReactReq_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserReactReq_ReqBy FOREIGN KEY (RequestedByUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserReactReq_DecBy FOREIGN KEY (FinalDecisionByUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserReactReq_ReBy FOREIGN KEY (ReactivatedByUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnUserReactReq_St CHECK (RequestStatusCode IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'REACTIVATED')),
    CONSTRAINT CK_TrnUserReactReq_Act CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserReactReq_UserOn
    ON TblTrnRBACUserReactRequest(UserUno, RequestOn DESC);

CREATE TABLE TblTrnRBACUserReactApproval (
    UserReactApprovalUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserReactRequestUno BIGINT NOT NULL,
    ApprovalLevelNo     SMALLINT DEFAULT 1 NOT NULL,
    ApproverUserUno     BIGINT NOT NULL,
    ApprovalStatusCode  VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    DecisionOn          TIMESTAMP,
    DecisionCommentEn   VARCHAR(1000),
    DecisionCommentAr   VARCHAR(1000),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnUserReactApr_Req FOREIGN KEY (UserReactRequestUno)
        REFERENCES TblTrnRBACUserReactRequest(UserReactRequestUno),
    CONSTRAINT FK_TrnUserReactApr_Usr FOREIGN KEY (ApproverUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT UQ_TrnUserReactApr_Lvl UNIQUE (UserReactRequestUno, ApprovalLevelNo, ApproverUserUno),
    CONSTRAINT CK_TrnUserReactApr_St CHECK (ApprovalStatusCode IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CK_TrnUserReactApr_Act CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserReactApr_Req
    ON TblTrnRBACUserReactApproval(UserReactRequestUno);

-- Separate history of user account expiration and reactivation events.
CREATE TABLE TblTrnRBACUserExpiryHist (
    UserExpiryHistUno    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno              BIGINT NOT NULL,
    ExpiredOn            TIMESTAMP NOT NULL,
    ExpirySourceCode     VARCHAR(30) DEFAULT 'ACCOUNT_EXPIRED' NOT NULL,
    ReactivatedOn        TIMESTAMP,
    ReactivatedBy        VARCHAR(128),
    UserReactRequestUno  BIGINT,
    EventCommentEn       VARCHAR(1000),
    EventCommentAr       VARCHAR(1000),
    IsActive             SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn           TIMESTAMP,
    InactivatedOn        TIMESTAMP,
    InactivatedBy        VARCHAR(128),
    ActivatedOn          TIMESTAMP,
    ActivatedBy          VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy            VARCHAR(128),
    ModifiedOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy           VARCHAR(128),
    DeletedOn            TIMESTAMP,
    DeletedBy            VARCHAR(128),
    CONSTRAINT FK_TrnUserExp_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserExp_Req FOREIGN KEY (UserReactRequestUno) REFERENCES TblTrnRBACUserReactRequest(UserReactRequestUno),
    CONSTRAINT CK_TrnUserExp_Source CHECK (
        ExpirySourceCode IN ('ACCOUNT_EXPIRED', 'MANUAL_INACTIVATION', 'POLICY_EXPIRY')
    ),
    CONSTRAINT CK_TrnUserExp_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserExp_UserOn
    ON TblTrnRBACUserExpiryHist(UserUno, ExpiredOn DESC);


-- User access review campaign for compliance (periodic certification).
CREATE TABLE TblTrnRBACUserReviewCampaign (
    UserReviewCampaignUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReviewCode          VARCHAR(40) NOT NULL,
    ReviewNameEn        VARCHAR(200) NOT NULL,
    ReviewNameAr        VARCHAR(200),
    ReviewTypeCode      VARCHAR(30) NOT NULL,
    ScopeTypeCode       VARCHAR(30) NOT NULL,
    CampaignOwnerUserUno BIGINT,
    ReviewStartOn       TIMESTAMP NOT NULL,
    ReviewDueOn         TIMESTAMP NOT NULL,
    ReviewClosedOn      TIMESTAMP,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT UQ_TrnUserReviewCamp_Code UNIQUE (ReviewCode),
    CONSTRAINT FK_TrnUserReviewCamp_Owner FOREIGN KEY (CampaignOwnerUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnUserReviewCamp_Type CHECK (ReviewTypeCode IN ('PERIODIC', 'EVENT_BASED', 'ADHOC')),
    CONSTRAINT CK_TrnUserReviewCamp_Scope CHECK (ScopeTypeCode IN ('ALL_USERS', 'DEPARTMENT', 'DIVISION', 'ROLE')),
    CONSTRAINT CK_TrnUserReviewCamp_Dates CHECK (ReviewDueOn >= ReviewStartOn),
    CONSTRAINT CK_TrnUserReviewCamp_IsActive CHECK (IsActive IN (0, 1))
);

CREATE TABLE TblTrnRBACUserReviewItem (
    UserReviewItemUno   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserReviewCampaignUno BIGINT NOT NULL,
    ReviewUserUno       BIGINT NOT NULL,
    ReviewerUserUno     BIGINT NOT NULL,
    AccessTypeCode VARCHAR(20) NOT NULL,
    RoleUno             BIGINT,
    UserGroupUno        BIGINT,
    DecisionCode        VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    DecisionCommentEn   VARCHAR(1000),
    DecisionCommentAr   VARCHAR(1000),
    DecisionOn          TIMESTAMP,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnUserReviewItem_Camp FOREIGN KEY (UserReviewCampaignUno) REFERENCES TblTrnRBACUserReviewCampaign(UserReviewCampaignUno),
    CONSTRAINT FK_TrnUserReviewItem_User FOREIGN KEY (ReviewUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserReviewItem_Reviewer FOREIGN KEY (ReviewerUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserReviewItem_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnUserReviewItem_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT CK_TrnUserReviewItem_AType CHECK (AccessTypeCode IN ('ROLE', 'GROUP')),
    CONSTRAINT CK_TrnUserReviewItem_Dec CHECK (DecisionCode IN ('PENDING', 'APPROVE', 'REVOKE', 'EXCEPTION')),
    CONSTRAINT CK_TrnUserReviewItem_ARef CHECK (
        (AccessTypeCode = 'ROLE' AND RoleUno IS NOT NULL AND UserGroupUno IS NULL) OR
        (AccessTypeCode = 'GROUP' AND UserGroupUno IS NOT NULL AND RoleUno IS NULL)
    ),
    CONSTRAINT CK_TrnUserReviewItem_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserReviewItem_Camp ON TblTrnRBACUserReviewItem(UserReviewCampaignUno);
CREATE INDEX IX_TrnUserReviewItem_User ON TblTrnRBACUserReviewItem(ReviewUserUno);
CREATE INDEX IX_TrnUserReviewItem_Reviewer ON TblTrnRBACUserReviewItem(ReviewerUserUno);

CREATE TABLE TblTrnRBACUserReviewAudit (
    UserReviewAuditUno  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserReviewCampaignUno BIGINT NOT NULL,
    UserReviewItemUno   BIGINT,
    AuditActionCode     VARCHAR(30) NOT NULL,
    AuditActionOn       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ActorUserUno        BIGINT,
    DetailJson          JSONB,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnUserReviewAudit_Camp FOREIGN KEY (UserReviewCampaignUno) REFERENCES TblTrnRBACUserReviewCampaign(UserReviewCampaignUno),
    CONSTRAINT FK_TrnUserReviewAudit_Item FOREIGN KEY (UserReviewItemUno) REFERENCES TblTrnRBACUserReviewItem(UserReviewItemUno),
    CONSTRAINT FK_TrnUserReviewAudit_Actor FOREIGN KEY (ActorUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnUserReviewAudit_Action CHECK (
        AuditActionCode IN ('CAMPAIGN_CREATED', 'ITEM_ASSIGNED', 'DECISION_SUBMITTED', 'DECISION_UPDATED', 'CAMPAIGN_CLOSED')
    ),
    CONSTRAINT CK_TrnUserReviewAudit_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserReviewAudit_CampOn
    ON TblTrnRBACUserReviewAudit(UserReviewCampaignUno, AuditActionOn DESC);

CREATE TABLE TblTrnRBACRoleCountryScope (
    RoleCountryScopeUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleUno             BIGINT NOT NULL,
    CountryUno          BIGINT NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnRoleCtry_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRoleCtry_Country FOREIGN KEY (CountryUno) REFERENCES TblMstRBACCountry(CountryUno),
    CONSTRAINT UQ_TrnRoleCtry UNIQUE (RoleUno, CountryUno),
    CONSTRAINT CK_TrnRoleCtry_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnRoleCtry_Country ON TblTrnRBACRoleCountryScope(CountryUno);

CREATE TABLE TblTrnRBACRoleEmbassyScope (
    RoleEmbassyScopeUno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleUno             BIGINT NOT NULL,
    EmbassyUno          BIGINT NOT NULL,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnRoleEmb_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnRoleEmb_Embassy FOREIGN KEY (EmbassyUno) REFERENCES TblMstRBACEmbassy(EmbassyUno),
    CONSTRAINT UQ_TrnRoleEmb UNIQUE (RoleUno, EmbassyUno),
    CONSTRAINT CK_TrnRoleEmb_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnRoleEmb_Embassy ON TblTrnRBACRoleEmbassyScope(EmbassyUno);

CREATE TABLE TblTrnRBACUserRole (
    UserRoleUno         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserUno             BIGINT NOT NULL,
    RoleUno             BIGINT NOT NULL,
    ValidFrom           DATE DEFAULT CURRENT_DATE NOT NULL,
    ValidTo             DATE,
    AssignedReason      VARCHAR(500),
    AssignedAt          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AssignedBy          VARCHAR(128),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnUserRole_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT FK_TrnUserRole_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_TrnUserRole UNIQUE (UserUno, RoleUno),
    CONSTRAINT CK_TrnUserRole_Dates CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom),
    CONSTRAINT CK_TrnUserRole_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnUserRole_Role ON TblTrnRBACUserRole(RoleUno);

CREATE TABLE TblTrnRBACGroupMembership (
    GroupMembershipUno  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserGroupUno        BIGINT NOT NULL,
    UserUno             BIGINT NOT NULL,
    MembershipSourceCode  VARCHAR(30) DEFAULT 'ORG_CHART' NOT NULL,
    ValidFrom           DATE DEFAULT CURRENT_DATE NOT NULL,
    ValidTo             DATE,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnGroupMem_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnGroupMem_User FOREIGN KEY (UserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT UQ_TrnGroupMembership UNIQUE (UserGroupUno, UserUno),
    CONSTRAINT CK_TrnGroupMem_Source CHECK (MembershipSourceCode IN ('ORG_CHART', 'DIRECTORY_SYNC', 'MANUAL')),
    CONSTRAINT CK_TrnGroupMem_Dates CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom),
    CONSTRAINT CK_TrnGroupMem_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnGroupMem_User ON TblTrnRBACGroupMembership(UserUno);

CREATE TABLE TblTrnRBACGroupRole (
    GroupRoleUno        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserGroupUno        BIGINT NOT NULL,
    RoleUno             BIGINT NOT NULL,
    AssignedAt          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AssignedBy          VARCHAR(128),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnGroupRole_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnGroupRole_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT UQ_TrnGroupRole UNIQUE (UserGroupUno, RoleUno),
    CONSTRAINT CK_TrnGroupRole_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnGroupRole_Role ON TblTrnRBACGroupRole(RoleUno);

-- GranteeTypeCode='ROLE'  => RoleUno is used
-- GranteeTypeCode='GROUP' => UserGroupUno is used
CREATE TABLE TblTrnRBACPermission (
    PermissionUno       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GranteeTypeCode VARCHAR(20) NOT NULL,
    RoleUno             BIGINT,
    UserGroupUno        BIGINT,
    ActionUno           BIGINT NOT NULL,
    GrantAcess           CHAR(1) DEFAULT 'Y' NOT NULL,
    GrantedAt           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    GrantedBy           VARCHAR(128),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnPerm_Role FOREIGN KEY (RoleUno) REFERENCES TblMstRBACRole(RoleUno),
    CONSTRAINT FK_TrnPerm_Group FOREIGN KEY (UserGroupUno) REFERENCES TblMstRBACUserGroup(UserGroupUno),
    CONSTRAINT FK_TrnPerm_Action FOREIGN KEY (ActionUno) REFERENCES TblMstRBACAction(ActionUno),
    CONSTRAINT CK_TrnPerm_Grantee CHECK (GranteeTypeCode IN ('ROLE', 'GROUP')),
    CONSTRAINT CK_TrnPerm_GrantAcess CHECK (GrantAcess IN ('Y', 'N')),
    CONSTRAINT CK_TrnPerm_GranteeRef CHECK (
        (GranteeTypeCode = 'ROLE' AND RoleUno IS NOT NULL AND UserGroupUno IS NULL) OR
        (GranteeTypeCode = 'GROUP' AND UserGroupUno IS NOT NULL AND RoleUno IS NULL)
    ),
    CONSTRAINT UQ_TrnPermission UNIQUE (GranteeTypeCode, RoleUno, UserGroupUno, ActionUno),
    CONSTRAINT CK_TrnPerm_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnPerm_Action ON TblTrnRBACPermission(ActionUno);
CREATE INDEX IX_TrnPerm_Role ON TblTrnRBACPermission(RoleUno);
CREATE INDEX IX_TrnPerm_Group ON TblTrnRBACPermission(UserGroupUno);

-- Dedicated audit trail for permission modifications.
CREATE TABLE TblTrnRBACPermissionAudit (
    PermissionAuditUno  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PermissionUno       BIGINT,
    AuditActionCode     VARCHAR(10) NOT NULL,
    ChangedOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ChangedBy           VARCHAR(128),
    ChangedByUserUno    BIGINT,
    OldGranteeTypeCode  VARCHAR(20),
    OldRoleUno          BIGINT,
    OldUserGroupUno     BIGINT,
    OldActionUno        BIGINT,
    OldGrantAcess        CHAR(1),
    OldIsActive         SMALLINT,
    OldDeletedOn        TIMESTAMP,
    NewGranteeTypeCode  VARCHAR(20),
    NewRoleUno          BIGINT,
    NewUserGroupUno     BIGINT,
    NewActionUno        BIGINT,
    NewGrantAcess        CHAR(1),
    NewIsActive         SMALLINT,
    NewDeletedOn        TIMESTAMP,
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnPermAudit_User FOREIGN KEY (ChangedByUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnPermAudit_Action CHECK (AuditActionCode IN ('INSERT', 'UPDATE', 'DELETE')),
    CONSTRAINT CK_TrnPermAudit_GOld CHECK (OldGrantAcess IS NULL OR OldGrantAcess IN ('Y', 'N')),
    CONSTRAINT CK_TrnPermAudit_GNew CHECK (NewGrantAcess IS NULL OR NewGrantAcess IN ('Y', 'N')),
    CONSTRAINT CK_TrnPermAudit_IAOld CHECK (OldIsActive IS NULL OR OldIsActive IN (0, 1)),
    CONSTRAINT CK_TrnPermAudit_IANew CHECK (NewIsActive IS NULL OR NewIsActive IN (0, 1)),
    CONSTRAINT CK_TrnPermAudit_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnPermAudit_PermOn
    ON TblTrnRBACPermissionAudit(PermissionUno, ChangedOn DESC);
CREATE INDEX IX_TrnPermAudit_User
    ON TblTrnRBACPermissionAudit(ChangedByUserUno);


CREATE TABLE TblTrnRBACAuditLog (
    AuditUno            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EventTs             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ActorUserUno        BIGINT,
    EventTypeCode         VARCHAR(60) NOT NULL,
    EntityTypeCode        VARCHAR(60) NOT NULL,
    EntityPk            VARCHAR(120),
    DetailJson          JSONB,
    IpAddress           VARCHAR(64),
    UserAgent           VARCHAR(1000),
    IsActive            SMALLINT DEFAULT 1 NOT NULL,
    InactiveOn          TIMESTAMP,
    InactivatedOn       TIMESTAMP,
    InactivatedBy       VARCHAR(128),
    ActivatedOn         TIMESTAMP,
    ActivatedBy         VARCHAR(128),
    InactivationReasonEn VARCHAR(1000),
    InactivationReasonAr VARCHAR(1000),
    EnteredOn           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EnteredBy           VARCHAR(128),
    ModifiedOn          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedBy          VARCHAR(128),
    DeletedOn           TIMESTAMP,
    DeletedBy           VARCHAR(128),
    CONSTRAINT FK_TrnAudit_Actor FOREIGN KEY (ActorUserUno) REFERENCES TblMstRBACUser(UserUno),
    CONSTRAINT CK_TrnAudit_IsActive CHECK (IsActive IN (0, 1))
);

CREATE INDEX IX_TrnAudit_EventTs ON TblTrnRBACAuditLog(EventTs);
CREATE INDEX IX_TrnAudit_Actor ON TblTrnRBACAuditLog(ActorUserUno);
CREATE INDEX IX_TrnAudit_Entity ON TblTrnRBACAuditLog(EntityTypeCode, EntityPk);

-- ============================================================
-- 3) HELPER VIEWS
-- ============================================================
CREATE OR REPLACE VIEW VRBACUserUsageDailyStat AS
SELECT
    DATE_TRUNC('day', A.ActivityOn)::date AS UsageOn,
    A.UserUno,
    A.PageUno,
    A.ActionUno,
    COUNT(1) AS TotalEventCount,
    SUM(CASE WHEN A.ActivityTypeCode = 'PAGE_VIEW' THEN 1 ELSE 0 END) AS PageViewCount,
    SUM(CASE WHEN A.ActivityTypeCode = 'ACTION_EXECUTE' THEN 1 ELSE 0 END) AS ActionExecCount,
    SUM(CASE WHEN COALESCE(A.IsAuthorized, 1) = 0 THEN 1 ELSE 0 END) AS UnauthorizedCount
FROM TblTrnRBACUserActivity A
WHERE A.IsActive = 1
  AND A.DeletedOn IS NULL
GROUP BY DATE_TRUNC('day', A.ActivityOn)::date, A.UserUno, A.PageUno, A.ActionUno;

CREATE OR REPLACE VIEW VRBACAppUsageDailyStat AS
SELECT
    DATE_TRUNC('day', A.ActivityOn)::date AS UsageOn,
    A.ModuleUno,
    A.PageUno,
    A.ActionUno,
    COUNT(1) AS TotalEventCount,
    COUNT(DISTINCT A.UserUno) AS DistinctUserCount,
    SUM(CASE WHEN A.ActivityTypeCode = 'PAGE_VIEW' THEN 1 ELSE 0 END) AS PageViewCount,
    SUM(CASE WHEN A.ActivityTypeCode = 'ACTION_EXECUTE' THEN 1 ELSE 0 END) AS ActionExecCount
FROM TblTrnRBACUserActivity A
WHERE A.IsActive = 1
  AND A.DeletedOn IS NULL
GROUP BY DATE_TRUNC('day', A.ActivityOn)::date, A.ModuleUno, A.PageUno, A.ActionUno;

-- Effective user actions from:
--   a) Direct user-role permission
--   b) Group-role permission
--   c) Direct group permission
CREATE OR REPLACE VIEW VRBACEffectiveUserAction AS
SELECT DISTINCT
    U.UserUno,
    P.ActionUno,
    'USER_ROLE' AS SourceType
FROM TblMstRBACUser U
JOIN TblTrnRBACUserRole UR
  ON UR.UserUno = U.UserUno
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCode = 'ROLE'
 AND P.RoleUno = UR.RoleUno
WHERE U.IsActive = 1
  AND U.DeletedOn IS NULL
  AND UR.IsActive = 1
  AND UR.DeletedOn IS NULL
  AND P.IsActive = 1
  AND P.DeletedOn IS NULL
  AND P.GrantAcess = 'Y'
  AND (UR.ValidTo IS NULL OR UR.ValidTo >= CURRENT_DATE)

UNION ALL

SELECT DISTINCT
    GM.UserUno,
    P.ActionUno,
    'GROUP_ROLE' AS SourceType
FROM TblTrnRBACGroupMembership GM
JOIN TblTrnRBACGroupRole GR
  ON GR.UserGroupUno = GM.UserGroupUno
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCode = 'ROLE'
 AND P.RoleUno = GR.RoleUno
WHERE GM.IsActive = 1
  AND GM.DeletedOn IS NULL
  AND GR.IsActive = 1
  AND GR.DeletedOn IS NULL
  AND P.IsActive = 1
  AND P.DeletedOn IS NULL
  AND P.GrantAcess = 'Y'
  AND (GM.ValidTo IS NULL OR GM.ValidTo >= CURRENT_DATE)

UNION ALL

SELECT DISTINCT
    GM.UserUno,
    P.ActionUno,
    'GROUP_PERMISSION' AS SourceType
FROM TblTrnRBACGroupMembership GM
JOIN TblTrnRBACPermission P
  ON P.GranteeTypeCode = 'GROUP'
 AND P.UserGroupUno = GM.UserGroupUno
WHERE GM.IsActive = 1
  AND GM.DeletedOn IS NULL
  AND P.IsActive = 1
  AND P.DeletedOn IS NULL
  AND P.GrantAcess = 'Y'
  AND (GM.ValidTo IS NULL OR GM.ValidTo >= CURRENT_DATE);

-- End of schema


-- ============================================================
-- PostgreSQL trigger functions and triggers
-- ============================================================

CREATE OR REPLACE FUNCTION fn_mstuser_valemaildomain()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    vdomain VARCHAR(255);
    vcount  BIGINT;
BEGIN
    IF NEW.EmailAddr IS NULL THEN
        RETURN NEW;
    END IF;

    IF POSITION('@' IN NEW.EmailAddr) <= 1 THEN
        RAISE EXCEPTION 'Invalid EmailAddr format.';
    END IF;

    vdomain := LOWER(TRIM(SPLIT_PART(NEW.EmailAddr, '@', 2)));

    IF vdomain IS NULL OR vdomain = '' OR POSITION('.' IN vdomain) = 0 THEN
        RAISE EXCEPTION 'Invalid EmailAddr format.';
    END IF;

    SELECT COUNT(1)
      INTO vcount
      FROM TblMstRBACAllowedEmailDomain d
     WHERE LOWER(d.EmailDomain) = vdomain
       AND d.IsActive = 1
       AND d.DeletedOn IS NULL;

    IF vcount = 0 THEN
        RAISE EXCEPTION 'Email domain not allowed in user master: %', vdomain;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER TRG_MstUser_ValEmailDomain
BEFORE INSERT OR UPDATE OF EmailAddr ON TblMstRBACUser
FOR EACH ROW
EXECUTE FUNCTION fn_mstuser_valemaildomain();


CREATE OR REPLACE FUNCTION fn_mstuser_setexpiry()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    vbasets TIMESTAMP;
BEGIN
    vbasets := COALESCE(NEW.EnteredOn, CURRENT_TIMESTAMP);

    IF NEW.StaffTypeCode IS NULL THEN
        NEW.StaffTypeCode := 'PERMANENT';
    END IF;

    IF NEW.AccountExpiryOn IS NULL THEN
        IF NEW.StaffTypeCode = 'EXTERNAL' THEN
            NEW.AccountExpiryOn := vbasets + INTERVAL '6 months';
        ELSE
            NEW.AccountExpiryOn := vbasets + INTERVAL '12 months';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER TRG_MstUser_SetExpiry
BEFORE INSERT OR UPDATE OF StaffTypeCode, EnteredOn, AccountExpiryOn ON TblMstRBACUser
FOR EACH ROW
EXECUTE FUNCTION fn_mstuser_setexpiry();


CREATE OR REPLACE FUNCTION fn_trnuseract_unauth()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    vunauthaccessuno BIGINT;
    vunauthcount     BIGINT;
    vopenbreachcnt   BIGINT;
    vaccesspointcode VARCHAR(20);
    vreasoncode      VARCHAR(40);
BEGIN
    IF COALESCE(NEW.IsAuthorized, 1) = 0 OR NEW.ActivityTypeCode = 'UNAUTHORIZED' THEN
        IF NEW.ActivityTypeCode = 'LOGIN' THEN
            vaccesspointcode := 'LOGIN';
            vreasoncode := 'LOGIN_DENIED';
        ELSIF NEW.ActivityTypeCode = 'API_CALL' THEN
            vaccesspointcode := 'API';
            vreasoncode := 'API_FORBIDDEN';
        ELSIF NEW.ActionUno IS NOT NULL THEN
            vaccesspointcode := 'ACTION';
            vreasoncode := 'ACTION_DENIED';
        ELSE
            vaccesspointcode := 'PAGE';
            vreasoncode := 'PAGE_DENIED';
        END IF;

        INSERT INTO TblTrnRBACUnauthAccess (
            UserUno, ActivityUno, AttemptOn, AccessPointCode, ModuleUno, PageUno, ActionUno,
            RoutePath, DenialReasonCode, ClientIpAddress, UserAgent, DetailJson,
            IsActive, EnteredOn, EnteredBy, ModifiedOn, ModifiedBy
        ) VALUES (
            NEW.UserUno, NEW.ActivityUno, NEW.ActivityOn, vaccesspointcode, NEW.ModuleUno, NEW.PageUno, NEW.ActionUno,
            NEW.RoutePath, vreasoncode, NEW.ClientIpAddress, NEW.UserAgent, NEW.DetailJson,
            1, CURRENT_TIMESTAMP, NEW.EnteredBy, CURRENT_TIMESTAMP, NEW.ModifiedBy
        ) RETURNING UnauthAccessUno INTO vunauthaccessuno;

        IF NEW.UserUno IS NOT NULL THEN
            SELECT COUNT(1)
              INTO vunauthcount
              FROM TblTrnRBACUnauthAccess ua
             WHERE ua.UserUno = NEW.UserUno
               AND ua.AttemptOn >= CURRENT_TIMESTAMP - INTERVAL '10 minutes'
               AND ua.DeletedOn IS NULL;

            IF vunauthcount >= 5 THEN
                SELECT COUNT(1)
                  INTO vopenbreachcnt
                  FROM TblTrnRBACSecurityIncident si
                 WHERE si.UserUno = NEW.UserUno
                   AND si.IncidentTypeCode = 'BRUTE_FORCE'
                   AND si.IncidentStatusCode IN ('OPEN', 'IN_PROGRESS')
                   AND si.IncidentOn >= CURRENT_TIMESTAMP - INTERVAL '10 minutes'
                   AND si.DeletedOn IS NULL;

                IF vopenbreachcnt = 0 THEN
                    INSERT INTO TblTrnRBACSecurityIncident (
                        UserUno, UnauthAccessUno, IncidentTypeCode, SeverityCode, IncidentOn,
                        IncidentStatusCode, DetectedByCode, DetailJson,
                        IsActive, EnteredOn, EnteredBy, ModifiedOn, ModifiedBy
                    ) VALUES (
                        NEW.UserUno, vunauthaccessuno, 'BRUTE_FORCE', 'HIGH', CURRENT_TIMESTAMP,
                        'OPEN', 'SYSTEM', '{"rule":"5 unauthorized attempts in 10 minutes"}',
                        1, CURRENT_TIMESTAMP, NEW.EnteredBy, CURRENT_TIMESTAMP, NEW.ModifiedBy
                    );
                END IF;
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER TRG_TrnUserAct_Unauth
AFTER INSERT ON TblTrnRBACUserActivity
FOR EACH ROW
EXECUTE FUNCTION fn_trnuseract_unauth();


CREATE OR REPLACE FUNCTION fn_mstuser_expiryhist()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    vhistuno BIGINT;
BEGIN
    IF NEW.InactivatedOn IS NOT NULL
       AND (OLD.InactivatedOn IS NULL OR OLD.InactivatedOn <> NEW.InactivatedOn) THEN
        INSERT INTO TblTrnRBACUserExpiryHist (
            UserUno, ExpiredOn, ExpirySourceCode, EventCommentEn,
            IsActive, EnteredOn, EnteredBy, ModifiedOn, ModifiedBy
        ) VALUES (
            NEW.UserUno, NEW.InactivatedOn, 'ACCOUNT_EXPIRED', NEW.InactivationReasonEn,
            1, CURRENT_TIMESTAMP, NEW.InactivatedBy, CURRENT_TIMESTAMP, NEW.ModifiedBy
        );
    END IF;

    IF NEW.ActivatedOn IS NOT NULL
       AND (OLD.ActivatedOn IS NULL OR OLD.ActivatedOn <> NEW.ActivatedOn) THEN
        SELECT MAX(UserExpiryHistUno)
          INTO vhistuno
          FROM TblTrnRBACUserExpiryHist
         WHERE UserUno = NEW.UserUno
           AND ReactivatedOn IS NULL
           AND DeletedOn IS NULL;

        IF vhistuno IS NOT NULL THEN
            UPDATE TblTrnRBACUserExpiryHist
               SET ReactivatedOn = NEW.ActivatedOn,
                   ReactivatedBy = NEW.ActivatedBy,
                   ModifiedOn = CURRENT_TIMESTAMP,
                   ModifiedBy = COALESCE(NEW.ModifiedBy, NEW.ActivatedBy)
             WHERE UserExpiryHistUno = vhistuno;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER TRG_MstUser_ExpiryHist
AFTER UPDATE OF InactivatedOn, ActivatedOn, InactivatedBy, ActivatedBy ON TblMstRBACUser
FOR EACH ROW
EXECUTE FUNCTION fn_mstuser_expiryhist();


CREATE OR REPLACE FUNCTION fn_trnrbacpermaudit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    vchangedby VARCHAR(128);
BEGIN
    IF TG_OP = 'INSERT' THEN
        vchangedby := COALESCE(NEW.ModifiedBy, NEW.EnteredBy);
        INSERT INTO TblTrnRBACPermissionAudit (
            PermissionUno, AuditActionCode, ChangedOn, ChangedBy,
            NewGranteeTypeCode, NewRoleUno, NewUserGroupUno, NewActionUno, NewGrantAcess, NewIsActive, NewDeletedOn,
            IsActive, EnteredOn, EnteredBy, ModifiedOn, ModifiedBy
        ) VALUES (
            NEW.PermissionUno, 'INSERT', CURRENT_TIMESTAMP, vchangedby,
            NEW.GranteeTypeCode, NEW.RoleUno, NEW.UserGroupUno, NEW.ActionUno, NEW.GrantAcess, NEW.IsActive, NEW.DeletedOn,
            1, CURRENT_TIMESTAMP, vchangedby, CURRENT_TIMESTAMP, vchangedby
        );
        RETURN NULL;
    ELSIF TG_OP = 'UPDATE' THEN
        vchangedby := COALESCE(NEW.ModifiedBy, OLD.ModifiedBy);
        INSERT INTO TblTrnRBACPermissionAudit (
            PermissionUno, AuditActionCode, ChangedOn, ChangedBy,
            OldGranteeTypeCode, OldRoleUno, OldUserGroupUno, OldActionUno, OldGrantAcess, OldIsActive, OldDeletedOn,
            NewGranteeTypeCode, NewRoleUno, NewUserGroupUno, NewActionUno, NewGrantAcess, NewIsActive, NewDeletedOn,
            IsActive, EnteredOn, EnteredBy, ModifiedOn, ModifiedBy
        ) VALUES (
            OLD.PermissionUno, 'UPDATE', CURRENT_TIMESTAMP, vchangedby,
            OLD.GranteeTypeCode, OLD.RoleUno, OLD.UserGroupUno, OLD.ActionUno, OLD.GrantAcess, OLD.IsActive, OLD.DeletedOn,
            NEW.GranteeTypeCode, NEW.RoleUno, NEW.UserGroupUno, NEW.ActionUno, NEW.GrantAcess, NEW.IsActive, NEW.DeletedOn,
            1, CURRENT_TIMESTAMP, vchangedby, CURRENT_TIMESTAMP, vchangedby
        );
        RETURN NULL;
    ELSE
        vchangedby := COALESCE(OLD.ModifiedBy, OLD.EnteredBy);
        INSERT INTO TblTrnRBACPermissionAudit (
            PermissionUno, AuditActionCode, ChangedOn, ChangedBy,
            OldGranteeTypeCode, OldRoleUno, OldUserGroupUno, OldActionUno, OldGrantAcess, OldIsActive, OldDeletedOn,
            IsActive, EnteredOn, EnteredBy, ModifiedOn, ModifiedBy
        ) VALUES (
            OLD.PermissionUno, 'DELETE', CURRENT_TIMESTAMP, vchangedby,
            OLD.GranteeTypeCode, OLD.RoleUno, OLD.UserGroupUno, OLD.ActionUno, OLD.GrantAcess, OLD.IsActive, OLD.DeletedOn,
            1, CURRENT_TIMESTAMP, vchangedby, CURRENT_TIMESTAMP, vchangedby
        );
        RETURN NULL;
    END IF;
END;
$$;

CREATE TRIGGER TRG_TrnRBACPermAudit
AFTER INSERT OR UPDATE OR DELETE ON TblTrnRBACPermission
FOR EACH ROW
EXECUTE FUNCTION fn_trnrbacpermaudit();
